guardian/mobile-apps-article-templates

Gruntfile.js, bower.json, bower_components/chai/.bower.json, bower_components/chai/CONTRIBUTING.md, bower_components/chai/History.md, bower_components/chai/README.md, bower_components/chai/ReleaseNotes.md, bower_components/chai/bower.json, bower_components/chai/chai.js, bower_components/chai/component.json, bower_components/chai/karma.conf.js, bower_components/chai/karma.sauce.js, bower_components/chai/package.json, bower_components/chai/sauce.browsers.js, bower_components/mocha/.bower.json, bower_components/mocha/.editorconfig, bower_components/mocha/.mailmap, bower_components/mocha/CONTRIBUTING.md, bower_components/mocha/HISTORY.md, bower_components/mocha/LICENSE, bower_components/mocha/README.md, bower_components/mocha/bower.json, bower_components/mocha/media/logo.svg, bower_components/mocha/mocha.css, bower_components/mocha/mocha.js, package.json, test/server.js, test/unit/common.js, test/unit/runner.html, test/unit/runner.js
=> Automation

ArticleTemplates/audioTemplate.html
=> Add id to audio slider knob

test/unit/runner.html
=> test-branch: just to test the mergin workflow

test/unit/twitter.js
=> test-branch-2: removed trailing space from js

ArticleTemplates/audioTemplate.html
=> add id to audio player icon

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/interactiveTemplate.html, test/unit/common.js
=> GIA-3464: Full Page Interactives Template

ArticleTemplates/assets/scss/base/_typography.scss, ArticleTemplates/assets/scss/helpers/_variables.scss
Renamed fonts to match NGW naming
=> GIA-3464: New template for full screen interactives

ArticleTemplates/articleTemplateImage.html
This PR allows displaying clean credits to an article image.
=> GIA-3120 correct credit caption display

README.md
The android source tree was re-organized recently. This patch updates
the reference.
=> Update android path to submodule

ArticleTemplates/galleryTemplate.html
=> fixing breakage on top of galleryTemplate

ArticleTemplates/articleTemplateCommentCount.html
Required for UI tests in the apps
@jorgeazevedo @AleLudovici
=> Added id to comment count

circle.yml
=> Update circle.yml to fetch latest changes on master

ArticleTemplates/articleTemplate.html, ArticleTemplates/audioTemplate.html, ArticleTemplates/commentsTemplate.html, ArticleTemplates/cricketTemplate.html, ArticleTemplates/errorExpiredContent.html, ArticleTemplates/footballTemplate.html, ArticleTemplates/galleryTemplate.html, ArticleTemplates/interactiveTemplate.html, ArticleTemplates/liveblogTemplate.html, ArticleTemplates/videoTemplate.html, test/fixture/article-tone-feature-immersive-embed.html, test/fixture/article-tone-feature-immersive.html, test/fixture/article-tone-feature.html, test/fixture/article-tone-news-youtube.html, test/fixture/article-tone-news.html, test/fixture/audio-tone-podcast.html, test/fixture/gallery-tone-media.html
Fix issue where __TEST_SPEC__ placeholder is wrapped in double quotes and double quotes in test object are not escaped
=>  __TEST_SPEC__ unescaped bug

ArticleTemplates/simpleBodyTemplatePrepopHelpAndroid.html, ArticleTemplates/simpleBodyTemplatePrepopHelpWindows.html
Just email address updated to app.feeback@theguardian.com
=> updated feeback email address

package.json
Probably my Node.js background, but the first think I do after looking at a README for a project is look at the package.json.
I have filled out the scripts bit to be a bit more helpful (for me).
If you don't want these changes, feel free to close this PR - its just a suggestion.
=> Adding scripts to package.json

ArticleTemplates/simpleBodyTemplatePrepopHelpAndroid.html, ArticleTemplates/simpleBodyTemplatePrepopHelpWindows.html
Change the email address on the Android help page and pre-populate the subject line.
[AND-11652](https://theguardian.atlassian.net/browse/AND-11652)
=> Update help email (AND-11652)

package.json, yarn.lock
As referenced here https://github.com/yarnpkg/yarn/issues/1016
=> Fix yarn on circleci

.gitignore, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/creativeInjector.js, ArticleTemplates/liveblogTemplate.html, ArticleTemplates/liveblogTemplateBlock.html, ArticleTemplates/liveblogTemplateContributionsEpic.html, test/spec/unit/bootstraps/liveblogTest.js
This PR:
- Adds the placeholder elements for Contributions Epic in liveblog
- Makes sure that the injected element is tracked
Again, wasn't sure if I should include the changed JS in the PR or not (whether it should be commited). Let me know! Its no trouble to commit it and add it to this PR
=> Contributions Epic in the liveblog

circle.sh
The last build failed because the git commands in `circle.sh` were not doing quite the right thing now. This should do the trick, but I will merge after the build to test it.
=> Editing git commands for release

circle.sh
Deployed to master fine, but not release so hopefully this will fix it. Might have to force push, but hopefully we can avoid doing that.
=> Fixing deploy to release

circle.sh
=> uncommenting if statement as everything should work

README.md
Looks nice and links to our build.
cc @GHaberis @SiAdcock
=> Adding the circle ci badge to the readme

circle.sh, circle.yml, package.json
On merging into Master Circle CI will generate built assets and update version number and merge these updates into Release. Once this is done it will publish Release to NPM.
=> Update CI settings to publish to NPM

circle.sh
@NataliaLKB this should show the version number in the commit message.
=> Show package version in commit message

ArticleTemplates/assets/js/modules/quiz.js, test/fixture/article-tone-news-personality-quiz.html
A bug was reported against this quiz on apps https://www.theguardian.com/politics/2017/jun/06/quiz-which-partys-general-election-manifesto-are-you.
After looking into it I found that some answers were attributed to multiple answer buckets (the data-buckets attribute in the HTML would have the value "C, F" rather than "C". This is scenario that wasn't supported by the app templates.
This change fixes that.
=> handle multiple answer buckets per answer

ArticleTemplates/simpleBodyTemplatePrepopCancelAppleSubscription.html
See https://theguardian.atlassian.net/browse/GLA-115
=> Add simpleBodyTemplatePrepopCancelAppleSubscription.html file

ArticleTemplates/simpleBodyTemplatePrepopCancelAppleSubscription.html
See https://github.com/guardian/ios-live/pull/3385
=> Copy changes to simpleBodyTemplatePrepopCancelAppleSubscription.html

.gitignore, README.md, config.sample.js
- remove last refs to `config.js`
- fix typo in readme
=> Small repo tidy up

README.md
I've updated the instructions for mobile apps development to use our preferred method -- comments welcome
CC @GHaberis @SiAdcock @jorgeazevedo @guardian/ios-developers @guardian/android-developers
=> Update instructions for iOS/Android development

ArticleTemplates/assets/js/modules/ads.js
Fix issue with ad position calculation introduced in here https://github.com/guardian/mobile-apps-article-templates/pull/667/files
=> Fix ad position on android 4.2

ArticleTemplates/assets/scss/base/_reset.scss
This is copied verbatim from the reset styles in frontend
=> Add reset styles for buttons

ArticleTemplates/footballTemplate.html, ArticleTemplates/footballTemplateMatchSummary.html
This allows the apps to use their own native header if they want to.
@ddramowicz
=> Move match summary div into its own template

ArticleTemplates/simpleBodyTemplatePrepopCancelDigipackSubscription.html
Copy coming from [here](https://www.theguardian.com/info/2014/aug/06/guardian-observer-digital-subscriptions-faq).
=> Add pre-populated template for Digipack cancellation

.gitignore
Adds `package-lock.json` to `.gitignore`
=> Ignore the package lock file

ArticleTemplates/assets/scss/base/_global.scss, ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss, ArticleTemplates/assets/scss/garnett-layout/_article--shared.scss, ArticleTemplates/assets/scss/garnett-layout/_article.scss, ArticleTemplates/assets/scss/garnett-modules/_sponsorship.scss, ArticleTemplates/assets/scss/garnett-modules/content/_standfirst.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-style-async.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/modules/_advert-slot.scss
Updates text sizes and main body column width for tablet. The main risk here is the update to the sponsorship styles —needed to adjust this ad placeholder when the text column changed—, but everything is looking good in fixtures…
=> text sizes

.gitignore, ArticleTemplates/assets/scss/garnett-base/_iconography.scss, ArticleTemplates/assets/scss/garnett-modules/_related-content.scss, ArticleTemplates/assets/scss/garnett-modules/content/_prose.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss
Garnett - Replace references to old icons in `.scss` to new icons.
=> Garnett - Replace icons

ArticleTemplates/articleTemplateContainerImmersive.html, ArticleTemplates/assets/scss/garnett-modules/cricket/_match-summary.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_sport.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/garnett-type/_article.scss, ArticleTemplates/assets/scss/garnett-type/_immersive.scss, ArticleTemplates/assets/scss/garnett-type/_matchreport.scss, ArticleTemplates/assets/scss/layout/_cricket.scss, ArticleTemplates/cricketTemplate.html, ArticleTemplates/cricketTemplateHeader.html, ArticleTemplates/footballTemplateLiveblog.html, test/garnett-fixture/article-sport-cricket-deadblog.html, test/garnett-fixture/article-sport-cricket-liveblog.html, test/garnett-fixture/article-sport-football-liveblog.html, test/garnett-fixture/immersive-news.html, test/garnett-fixture/matchreport-sport.html
This updates Football liveblogs, Football match reports, Cricket deadblogs and Cricket liveblogs for Garnett.
I've also snuck in an update to the meta area of Immersive articles.
=> Garnett: Football and Cricket blogs

ArticleTemplates/assets/scss/garnett-layout/_article--shared.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-type/_guardianview.scss, test/garnett-fixture/article-news.html, test/garnett-fixture/guardianview-opinion.html
=> Garnett: guardianview type support

ArticleTemplates/assets/scss/garnett-modules/_related-content.scss
Temporarily hide related cards for Garnett release
=> Garnett: hide related cards

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
…adds pillar based play buttons
=> Adds pillar based play buttons

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
Use `$p-feature-headline` for feature article headlines.
=> Use feature headline colour

ArticleTemplates/assets/scss/garnett-type/_article.scss
Regular article standfirsts should be in bold, body text size.
=> Updated article standfirst style

ArticleTemplates/assets/scss/garnett-modules/_figure.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss
This updates figure caption typography, as requested by millions
=> Caption text

ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-type/_article.scss
Styles comment count on right side of meta area, and increases it's tappable area.
=> Style comment count

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-type/_analysis.scss
Adds the state-of-the-art headline underlines to analysis content types
=> Analysis headlines

ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss
updates figure captions in main media to have some left/right padding
=> Tweak figure padding

ArticleTemplates/assets/scss/modules/content/_review-rating.scss
=> Massively improves review star alignment

ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-type/_comment.scss
Comment count is now 12px from the right edge of the screen
=> Tweak alignment of comment count

ArticleTemplates/assets/scss/garnett-modules/external/_element.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss
Adds padding under main-media atoms…
=> Adds padding under main-media atoms

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
pillar colour play buttons on all pages, not just media
=> pillar colour play buttons on all pages, not just media

ArticleTemplates/assets/scss/modules/external/_element.scss
=> centre play buttons

ArticleTemplates/assets/js/bootstraps/audio.js
Reverts guardian/mobile-apps-article-templates#741
=> Revert "Handle Horizontal Swipe on Audio slider"

ArticleTemplates/assets/scss/garnett-pillar/_arts.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-pillar/_opinion.scss
Updates colour palette to match the latest changes in MAPI PR [#1084](https://github.com/guardian/mobile-apps-api/pull/1084)
=> Updates colour palette

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss, ArticleTemplates/assets/scss/garnett-pillar/_arts.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-pillar/_opinion.scss, ArticleTemplates/assets/scss/modules/content/_review-rating.scss
Makes the caption toggle icon yellow, and adjusts the size slightly
**Before**
**After**
=> Yellow caption icon

ArticleTemplates/assets/scss/garnett-modules/_alerts.scss, ArticleTemplates/assets/scss/garnett-modules/_avatar.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-type/_live.scss, test/garnett-fixture/analysis-opinion.html, test/garnett-fixture/article-arts.html
Makes the article meta and 'follow author' areas more compact
**Before**
**After**
=> Tighter meta area

ArticleTemplates/articleTemplateBylineImmersive.html, ArticleTemplates/articleTemplateContainerImmersive.html, ArticleTemplates/assets/scss/garnett-modules/_alerts.scss, ArticleTemplates/assets/scss/garnett-type/_immersive.scss, ArticleTemplates/assets/scss/helpers/_variables.scss, ArticleTemplates/assets/scss/layout/_article--liveblog.scss, package.json, test/garnett-fixture/immersive-arts.html, test/garnett-fixture/immersive-lifestyle.html, test/garnett-fixture/immersive-news.html, test/garnett-fixture/immersive-sport.html
Updates the immersive headline design.
**Before**
**After**
=> Immersive headline

ArticleTemplates/assets/scss/garnett-modules/_alerts.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
Fixes the alerts button when you're already following the person.
**Before**
**After**
=> Fix following button

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
=> The alert icon went on a little break, and now it's back and feeling quite refreshed actually, thanks

ArticleTemplates/assets/scss/garnett-type/_feature.scss
=> Bolder feature headlines

ArticleTemplates/liveblogTemplate.html
Right now they appear unstyled:
=> Enable atoms in liveblogs

test/garnett-fixture/collection.html
This just adds a collection fixture so we can update the collection design more easily.
I think I've made the right changes to use this HTML as a fixture. @GHaberis can you please check this is OK?
=> adds a collection fixture

test/garnett-fixture/immersive-news-video.html
This adds a fixture for an immersive feature with a video header for debugging. Note: this is currently not working on iOS
=> Adds immersive with video header fixture

ArticleTemplates/assets/js/bootstraps/campaign.js
I removed that line by mistake 😐 Sorry about that, @SLambrakis @mohammad-haque
=> Enable CORS

ArticleTemplates/assets/scss/garnett-type/_immersive.scss
Jira ticket: https://theguardian.atlassian.net/browse/MSS-347
Trello ticket: https://trello.com/c/xSxZ359p/282-bugs-with-pictures
Immersive header jumps up and down during animation
-----------
=> stop iframe contents growing and increasing header height

ArticleTemplates/assets/js/modules/more-tags.js
Inform native layer of position on show more event rather than waiting for the poller.
----------
=> Jw related content tags bug

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
=> stop hiding captions

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/modules/_more.scss, ArticleTemplates/assets/scss/modules/blocks/_comment.scss, ArticleTemplates/commentsTemplatePreview.html
- View more comments to be pillar colour
- Recommended comments using pillar colour
- Reply to comment has stylesheets and uses `Guardian Egyptian Web`
------------
=> Comment preview improvements

ArticleTemplates/assets/scss/garnett-tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/garnett-type/_live.scss
Still some tweaks required (increasing contrast more, especially the more button)
Before:
After:
=> keep contrast on dead blogs

ArticleTemplates/assets/scss/modules/blocks/_comment.scss, ArticleTemplates/commentsTemplateBlock.html
⚠️ Requires https://github.com/guardian/ios-live/pull/4037 to populate the placeholder
=> Staff comments

ArticleTemplates/assets/scss/garnett-modules/content/_prose.scss
=> Live blog icons

ArticleTemplates/assets/scss/garnett-layout/_article.scss
| Android | iOS |
| ---- | ---- |
|![screen shot 2018-08-24 at 11 27 58](https://user-images.githubusercontent.com/11618797/44591508-d3416e80-a7b5-11e8-9b1b-77f9e76a8935.png)|![screen shot 2018-08-24 at 12 04 53](https://user-images.githubusercontent.com/11618797/44591517-d6d4f580-a7b5-11e8-832e-4ec7e46e2245.png)|
|![screen shot 2018-08-24 at 11 33 43](https://user-images.githubusercontent.com/11618797/44591767-814d1880-a7b6-11e8-84c2-3121e335c600.png)|![screen shot 2018-08-24 at 12 03 29](https://user-images.githubusercontent.com/11618797/44591545-e7856b80-a7b5-11e8-99f4-cb0ac63bd021.png)|
|![screen shot 2018-08-24 at 11 34 54](https://user-images.githubusercontent.com/11618797/44591564-f53af100-a7b5-11e8-9a45-7615902ca876.png)|![screen shot 2018-08-24 at 11 59 …
=> apply missing padding to articles on android

ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
| ![screen shot 2018-09-05 at 10 40 14 2](https://user-images.githubusercontent.com/11618797/45106545-d7af4500-b12e-11e8-87f1-bfc0acf36ed9.png) | ![screen shot 2018-09-05 at 16 54 19](https://user-images.githubusercontent.com/11618797/45106551-dd0c8f80-b12e-11e8-98cf-b54f16bfcf97.png) |
=> add a min height as a fallback for no images

ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/type/_guardianlabs.scss, ArticleTemplates/assets/scss/type/_immersive.scss
| Before | After | 
| --- | --- |
| ![screen shot 2018-09-07 at 12 20 57](https://user-images.githubusercontent.com/11618797/45218162-832ad780-b29e-11e8-81ee-d9d446b6eba6.png) | ![screen shot 2018-09-07 at 12 55 08](https://user-images.githubusercontent.com/11618797/45218166-88882200-b29e-11e8-8285-7aaf8459a0f0.png) |
| ![after](https://user-images.githubusercontent.com/11618797/45218172-8d4cd600-b29e-11e8-9aaf-25c79477927e.png) | ![screen shot 2018-09-07 at 12 58 44](https://user-images.githubusercontent.com/11618797/45218175-9178f380-b29e-11e8-8316-7978d9f39d82.png) |
=> Jw guardianlabs edge case

ArticleTemplates/assets/scss/modules/content/_prose.scss
https://theguardian.atlassian.net/browse/MSS-476
| --- | --- |
| ![screen shot 2018-09-10 at 18 35 35](https://user-images.githubusercontent.com/11618797/45313973-60135880-b528-11e8-97a6-873fadc213bf.png) | ![screen shot 2018-09-10 at 18 10 33](https://user-images.githubusercontent.com/11618797/45313987-66a1d000-b528-11e8-9d5b-bf8a86331dcb.png) |
=> display following paragraph tag inline

ArticleTemplates/assets/scss/modules/_figure.scss
| --- | --- |
| ![img_5586](https://user-images.githubusercontent.com/11618797/45095973-513b3900-b117-11e8-9427-a34d5e04db93.png) | ![screen shot 2018-09-05 at 11 55 06](https://user-images.githubusercontent.com/11618797/45095982-56988380-b117-11e8-8f95-2bc5a7f28bb8.png) |
| ![img_5581](https://user-images.githubusercontent.com/11618797/45095993-60ba8200-b117-11e8-99f9-d5fc8838dc95.png) | ![screen shot 2018-09-05 at 11 56 14](https://user-images.githubusercontent.com/11618797/45096002-6617cc80-b117-11e8-8b5e-475ea9498d59.png) |
| ![img_5577](https://user-images.githubusercontent.com/11618797/45096014-6d3eda80-b117-11e8-88dc-875158ce7be0.png) | ![screen shot 2018-09-05 at 11 51 27](https://user-images.githubusercontent.com/11618797/45096026-729c2500-b117-11e8-9a8d-59d7af5 …
=> Remove additional figure styles

ArticleTemplates/assets/scss/type/_immersive.scss, ArticleTemplates/interactiveTemplate.html
Reverts guardian/mobile-apps-article-templates#844
=> Revert "Reduce css on interactives page"

ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/outbrain.scss
| --- | --- |
|  | <img width="335" alt="screen shot 2018-09-25 at 15 06 09" src="https://user-images.githubusercontent.com/11618797/46027689-5e2fc480-c0e6-11e8-98dc-9366ed2b57c1.png"> |
| | ![screen shot 2018-09-25 at 18 40 24](https://user-images.githubusercontent.com/11618797/46032610-04ce9200-c0f4-11e8-8dbb-571ea3874d38.png) |
| | ![screen shot 2018-09-25 at 18 40 40](https://user-images.githubusercontent.com/11618797/46032655-2596e780-c0f4-11e8-9551-27157846d876.png) |
=> 8pt grid outbrain

ArticleTemplates/assets/scss/modules/_alerts.scss, ArticleTemplates/assets/scss/modules/_atoms.scss
Reverts guardian/mobile-apps-article-templates#855
=> Revert "alerts and feedback atom"

ArticleTemplates/assets/js/bootstraps/audio.js, ArticleTemplates/assets/js/components/mobile-range-slider.js, ArticleTemplates/assets/scss/modules/_touchpoint.scss, ArticleTemplates/assets/scss/modules/media/_audio-player.scss, ArticleTemplates/assets/scss/pillar/_colour.scss
=> Templates media controls 

ArticleTemplates/assets/js/modules/comments.js
| --- | --- |
| ![screen shot 2018-10-08 at 14 13 57](https://user-images.githubusercontent.com/11618797/46617633-22005900-cb15-11e8-9563-40a54002f6e8.png) | ![screen shot 2018-10-08 at 14 59 11](https://user-images.githubusercontent.com/11618797/46617644-262c7680-cb15-11e8-8150-52085626cc2d.png) |
| ![screen shot 2018-10-08 at 14 14 21](https://user-images.githubusercontent.com/11618797/46617654-2af12a80-cb15-11e8-9afa-2acbc9e184dd.png) | ![screen shot 2018-10-08 at 14 59 56](https://user-images.githubusercontent.com/11618797/46617660-2f1d4800-cb15-11e8-880d-5470a5b05b76.png) |
=> iOS comment improvements

ArticleTemplates/assets/scss/layout/_article--audio.scss, ArticleTemplates/assets/scss/modules/_sponsorship.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/audioTemplate.html
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/47097028-60d69300-d228-11e8-8420-d46c40d9fb72.png" width="400" /> | <img src="https://user-images.githubusercontent.com/11618797/47097040-6af89180-d228-11e8-8d0b-01adc0d8dc6b.png" width="400" /> |
| <img src="https://user-images.githubusercontent.com/11618797/47097049-7350cc80-d228-11e8-8ab0-e2547da9885c.png" width="400" /> | <img src="https://user-images.githubusercontent.com/11618797/47097061-7a77da80-d228-11e8-9ee0-c94dafb23875.png" width="400" /> |
| <img src="https://user-images.githubusercontent.com/11618797/47097067-819ee880-d228-11e8-9f19-4b3a10f23247.png" width="400" /> | <img src="https://user-images.githubusercontent.com/11618797/47097090-8cf21400-d228-11e8-8d17-15855aeb749d.png" …
=> Position standfirst above audio article body

ArticleTemplates/assets/scss/type/_media-all.scss
| --- | --- |
| ![screen shot 2018-10-19 at 10 43 22](https://user-images.githubusercontent.com/11618797/47212554-78c92680-d390-11e8-8fe2-e260e21576ed.png) | ![screen shot 2018-10-19 at 10 43 37](https://user-images.githubusercontent.com/11618797/47212557-7c5cad80-d390-11e8-834f-19b9c185de01.png) |
| ![screen shot 2018-10-19 at 11 03 34](https://user-images.githubusercontent.com/11618797/47212566-81b9f800-d390-11e8-83d7-01cd520c4424.png) | ![screen shot 2018-10-19 at 11 08 59](https://user-images.githubusercontent.com/11618797/47212571-854d7f00-d390-11e8-8374-a3820db6fba1.png) |
=> Align content on large tablet screens

ArticleTemplates/assets/scss/pillar/_colour.scss
=> Liveblog author names

ArticleTemplates/assets/scss/type/_immersive.scss
https://theguardian.atlassian.net/browse/MSS-555
=> Keep immersive article headers black

ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/js/bootstraps/campaign.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/js/modules/more-tags.js, ArticleTemplates/assets/js/modules/twitter.js
toggle wouldn't work before iOS 10.3
=> Reposition ads and related content on layout changes

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48715223-6dc21a00-ec0c-11e8-943a-346119c52ca5.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48715226-6dc21a00-ec0c-11e8-921b-d618260c2670.png" width="300px" /> |
=> Photo essay captions bug

ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48848646-5dd94000-ed9c-11e8-9eac-371a4b85b96c.png"  width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48848663-6c275c00-ed9c-11e8-9aa7-55b46fd6c1ec.png" width="300px"/> |
| <img src="https://user-images.githubusercontent.com/11618797/48848696-83fee000-ed9c-11e8-8bc2-486ff8af6b3b.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48848739-a264db80-ed9c-11e8-9bae-b07fcc0e7258.png" width="300px"/> |
=> Immersive article caption padding

ArticleTemplates/assets/js/modules/comments.js
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48839768-6de52580-ed84-11e8-9b89-8b3f94020c79.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/48839839-b00e6700-ed84-11e8-8a6b-20e6c8c26121.png" width="300px" /> |
=> Hide incorrect comment count

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/type/_guardianlabs.scss
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48939107-18875080-ef0b-11e8-88b2-d07894fc72cf.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48939119-23da7c00-ef0b-11e8-9286-04bfe4c35d09.png" width="300px"/> |
| <img src="https://user-images.githubusercontent.com/11618797/48939145-3c4a9680-ef0b-11e8-8442-f0fd9a9fb0f2.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48939175-4d93a300-ef0b-11e8-9b5f-9b7848485f04.png" width="300px"/> |
=> Update labs to new background

ArticleTemplates/assets/scss/modules/_commentsHighlighted.scss, ArticleTemplates/assets/scss/modules/blocks/_comment.scss
=> Update font colours

ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/type/_feature.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/49578619-11683580-f942-11e8-8edb-9d7f1bdef7eb.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49578652-1e852480-f942-11e8-9a15-92f72e87c58a.png" width="300px" />|
=> Render interviews as features

ArticleTemplates/assets/scss/modules/external/_element.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/49934261-c613d100-fec5-11e8-8996-0d668b30519a.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49934276-d461ed00-fec5-11e8-99c4-27329ca630ff.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/49934288-de83eb80-fec5-11e8-8ea8-2083d088ec05.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49934305-eba0da80-fec5-11e8-8d4e-1407bdae8c2e.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/49934315-f3607f00-fec5-11e8-8623-2e0262c77b17.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49934518-7eda1000-fec6-11e8-8033-4895fe5822e7.png" …
=> Correct embed widths

ArticleTemplates/assets/scss/modules/_tabs.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/49997607-f15ff400-ff89-11e8-9a86-d54103495150.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49997616-f624a800-ff89-11e8-8ac0-0a73a8b0ea92.png" width="300px" />|
=> Football tab padding

ArticleTemplates/assets/js/modules/comments.js
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/49951223-5c112100-fef1-11e8-9af7-427f56b43e4c.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/49951199-4dc30500-fef1-11e8-97b2-3bd794b34e97.png" width="300px" />|
=> Hide loading icon when all comments fetched

ArticleTemplates/assets/scss/modules/external/_element.scss
=> reduce width on liveblogs

ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/modules/_commentsHighlighted.scss, ArticleTemplates/assets/scss/modules/blocks/_comment.scss, ArticleTemplates/commentsTemplateBlock.html, ArticleTemplates/commentsTemplateBlockHighlighted.html, ArticleTemplates/moduleComments.html
=> Comment icons

ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/twitter.js, ArticleTemplates/assets/js/modules/youtube.js
| --- | --- | 
| <img src="https://user-images.githubusercontent.com/11618797/50080504-2798b000-01e4-11e9-914a-b164fd0a3b57.png" width="300"/> | <img src="https://user-images.githubusercontent.com/11618797/50080529-38e1bc80-01e4-11e9-9c86-ab31b632daf8.png" width="300"/> |
=> Update youtube sdk position

ArticleTemplates/assets/scss/layout/_article--shared.scss, test/fixtures/feature-news-with-thumbnail.html
Fixes thumbnail size and position on large tablets
| --- | --- |
|<img src="https://user-images.githubusercontent.com/4561/50226501-3c6b7400-039b-11e9-9b87-969d81b9ee3c.png" width="375px" />|<img src="https://user-images.githubusercontent.com/4561/50226497-3a091a00-039b-11e9-9f10-b06012486738.png" width="375px" />|
=> Fixes thumbnail size and position on large tablets

ArticleTemplates/assets/js/modules/ads.js
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/50478448-0fd1e080-09c9-11e9-9afd-1f1e95311053.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/50478452-13fdfe00-09c9-11e9-8ed9-72f7f1529ed8.png" width="300px" />|
=> Check for overlapping adverts

ArticleTemplates/assets/js/modules/ads.js
Reverts guardian/mobile-apps-article-templates#898
=> Revert "Check for overlapping adverts"

ArticleTemplates/assets/scss/modules/witness/_embed.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/50565079-25c20700-0d23-11e9-9495-e062b5547f46.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/50565080-25c20700-0d23-11e9-8ec8-f6e04e16d0de.png" width="300px" />|
=> Improve newsletter sign up styles

ArticleTemplates/assets/scss/layout/_article--shared.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/50565377-3031d000-0d26-11e9-9af5-ee30fe2aef30.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/50565376-2f993980-0d26-11e9-9c21-0247537d2392.png" width="300px" />|
=> Fix tablet thumbnail bug

ArticleTemplates/assets/js/modules/comments.js
=> Show comment count

ArticleTemplates/assets/js/modules/rich-links.js
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/50588360-9f6c0900-0e79-11e9-803b-2d88e7d854f2.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/50588359-9ed37280-0e79-11e9-8bea-3fc86b30a6f5.png" width="300px" />|
=> Rich links next to images fix

ArticleTemplates/assets/js/modules/cards.js, package.json, yarn.lock
=> Remove flipsnap

ArticleTemplates/assets/scss/layout/_article--shared.scss
=> Hide contribution thumbnail for subscribers

ArticleTemplates/assets/js/modules/creativeInjector.js
- Inject if we have at least 10 paragraphs
- Inject after advert slot
=> Inject inline creatives

ArticleTemplates/assets/js/bootstraps/common.js
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/50828426-46005000-1339-11e9-93a4-a4ffa0d61567.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/50828443-53b5d580-1339-11e9-91ef-3f522dc131ed.png" width="300px" />|
=> Apply correct formstack styles

test/spec/unit/modules/ads.test.js
=> Fix JS tests

ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/layout/_football.scss, ArticleTemplates/assets/scss/modules/_interactive.scss, ArticleTemplates/assets/scss/modules/_more.scss, ArticleTemplates/assets/scss/modules/_tags.scss, ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/type/_live.scss, ArticleTemplates/assets/scss/type/_matchreport.scss, ArticleTemplates/assets/scss/type/_media-all.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/51315620-74251480-1a4a-11e9-8545-30bf0d9c6913.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/51315623-74bdab00-1a4a-11e9-9b80-5e0746bdfce9.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/51315622-74251480-1a4a-11e9-9812-c81457a0a37f.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/51315621-74251480-1a4a-11e9-8d7a-6c8e98b05d5c.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/51315625-74bdab00-1a4a-11e9-8721-e5af6b20fa74.png" width="300px" />| <img src="https://user-images.githubusercontent.com/11618797/51315845-0e855800-1a4b-11e9-8443-f01933c1f99f.png" …
=> Use standard app background in templates

ArticleTemplates/assets/js/bootstraps/common.js
=> Clear setupForm interval

ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/layout/_football.scss, ArticleTemplates/assets/scss/type/_live.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/51479177-6f7f9980-1d85-11e9-805b-0c8389fce43e.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/51479241-9dfd7480-1d85-11e9-839f-d66f32f03ad6.png" width="300px" />|
=> Unify tag colour styles

ArticleTemplates/assets/scss/layout/_football.scss, ArticleTemplates/assets/scss/modules/_inline-list.scss, ArticleTemplates/assets/scss/modules/_tabs.scss, ArticleTemplates/assets/scss/pillar/_sport.scss, ArticleTemplates/cricketTemplate.html, ArticleTemplates/footballTemplate.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/51187362-9ea09180-18d3-11e9-8b48-2df4df0878d2.png" width="300" />|<img src="https://user-images.githubusercontent.com/11618797/51187369-a6603600-18d3-11e9-928d-4e65049e96ae.png" width="300" />|
|<img src="https://user-images.githubusercontent.com/11618797/51187393-afe99e00-18d3-11e9-962b-dfe0497b83dd.png" width="300" />|<img src="https://user-images.githubusercontent.com/11618797/51187410-baa43300-18d3-11e9-99dc-a764ef6fbcaf.png" width="300" />|
|<img src="https://user-images.githubusercontent.com/11618797/51187434-c2fc6e00-18d3-11e9-8dbf-95c89ef4e7ae.png" width="300" />|<img src="https://user-images.githubusercontent.com/11618797/51187456-cbed3f80-18d3-11e9-8b8b-8764b8ac3017.png" width="300" …
=> Football and cricket standfirsts

ArticleTemplates/assets/scss/outbrain.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/51689939-8cb7a080-1fef-11e9-9a42-7a9c093e55b2.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/51689941-8cb7a080-1fef-11e9-95d0-db81dfb44e1a.png" width="300px" />|
=> Fix outbrain for iPad pro

ArticleTemplates/assets/scss/layout/_article--comment.scss, ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/type/_comment.scss
=> Clickable opinion links

ArticleTemplates/assets/js/boot.js, ArticleTemplates/assets/js/bootstraps/liveblog.js
Just noticed this when the gaps were being inserted, but the blocks weren't!
=> Fix some typos: liveblockInsertBlocks -> liveblogInsertBlocks

ArticleTemplates/assets/js/bootstraps/common.js
=> Update ad position on tab change

ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/outbrain.scss
=> Comment font

ArticleTemplates/assets/scss/modules/_interactive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/53341318-2336f480-3903-11e9-961b-fe4e86bdd526.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/53341324-27631200-3903-11e9-80c8-0af9d154c44d.jpg" width="300px" />|
=> Center offline interactive text

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54032930-e395c580-41aa-11e9-8fd8-4d003f7f16b9.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54032944-eb556a00-41aa-11e9-9366-a7bc380f3dc7.png" width="300px" />|
| <img src="https://user-images.githubusercontent.com/11618797/54032956-f8725900-41aa-11e9-8a41-87d80f0f690d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/54032998-1475fa80-41ab-11e9-859a-6defe9557c27.png" width="300px" /> |
=> Photo essay grid fix

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54036898-acc4ad00-41b4-11e9-9d58-c275ac828e6d.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54036904-b0f0ca80-41b4-11e9-897c-f4653062a6c0.png" width="300px" />|
=> Another photo essay style tweak

ArticleTemplates/assets/js/bootstraps/liveblog.js
=> Liveblog toggle

ArticleTemplates/assets/js/modules/youtube.js, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/pillar/_sport.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54138873-450e9c00-4418-11e9-8760-6e1ec3453481.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54138871-44760580-4418-11e9-81b8-a14a927eb468.png" width="300px" />|
=> Avoid duplicate video captions

ArticleTemplates/assets/js/modules/youtube.js, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/youtubeAtomPositionPlaceholder.html, ArticleTemplates/youtubeAtomWithVideoPosterImage.html, ArticleTemplates/youtubeAtomWithoutVideoPosterImage.html
=> Atom attribute clash

ArticleTemplates/assets/scss/modules/_figure.scss
=> Email signup captions

ArticleTemplates/assets/js/modules/creativeInjector.js
https://sentry.io/organizations/the-guardian/issues/876382376/?project=40557&query=is%3Aunresolved&statsPeriod=14d&utc=false
=> Undefined inject creative

ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/modules/blocks/_block.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/liveblogTemplateTitle.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54605445-2e33ff00-4a41-11e9-948b-4d408d126e2f.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54605450-3429e000-4a41-11e9-9293-a9ac73839e9a.png" width="300px" />|
=> liveblog design updates

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/modules/external/_element.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54683607-f775eb80-4b09-11e9-9856-a3306b2725cc.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54683632-065c9e00-4b0a-11e9-9ae9-e3a3e764b7d4.PNG" width="300px" />|
=> Full width embeds

ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/type/_live.scss
=> Keep byline author visible

ArticleTemplates/assets/scss/modules/_tabs.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54523655-e9886500-4967-11e9-8b83-71f96dcbd886.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54523734-23596b80-4968-11e9-96b2-0704d44bc6f7.png" width="300px" />|
=> football fixes

ArticleTemplates/assets/js/bootstraps/liveblog.js
=> Relative timestamps

test/spec/unit/bootstraps/liveblog.test.js
=> Update liveblog tests

ArticleTemplates/assets/scss/modules/content/_prose.scss
=> Liveblog quote colour

ArticleTemplates/assets/js/modules/twitter.js
Some tweets do not get enhanced in the liveblog.
This change keeps track of their heights and notifies the apps when they need to reposition ads, related cards and youtube videos.
=> Enhance all tweets

ArticleTemplates/assets/scss/modules/_key-events.scss, ArticleTemplates/assets/scss/modules/external/_d2-comment.scss, ArticleTemplates/assets/scss/pillar/_colour.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54941711-6cd82680-4f25-11e9-8476-ded1a4e8a780.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54941718-719cda80-4f25-11e9-972d-4d21ba23169d.png" width="300px" />|
=> Tablet backgrounds

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/modules/_figure.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/54935446-3ea01a00-4f18-11e9-92e6-81863731f18d.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54935473-4790eb80-4f18-11e9-8594-c940359b8a87.PNG" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/54935492-52e41700-4f18-11e9-963b-f86870e732c7.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/54935503-56779e00-4f18-11e9-9950-afe538467158.png" width="300px" />|
=> Increase size of thumbnail image

ArticleTemplates/assets/js/bootstraps/gallery.js, ArticleTemplates/assets/scss/type/_media-gallery.scss, ArticleTemplates/galleryTemplate.html
=> Dim background on image pinch

ArticleTemplates/assets/js/bootstraps/gallery.js
=> Track gallery pinch

ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/twitter.js
=> Enhance tweets on liveblog view more

ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/layout/_base-tone.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/55325242-59c0db80-547c-11e9-8b41-793f6830518b.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/55325250-5e858f80-547c-11e9-962e-ddb4d05686bb.png" width="300px" />|
=> Full width main media captions

ArticleTemplates/assets/js/bootstraps/common.js
=> Point to new sentry project

ArticleTemplates/assets/js/bootstraps/common.js, package-lock.json, package.json
We can put this in a conditional that's populated by the native layer.
=> Remove Sentry

ArticleTemplates/assets/js/bootstraps/liveblog.js
=> Revert enhance tweet on load more

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/_resizable.scss, ArticleTemplates/assets/scss/type/_media-gallery.scss, ArticleTemplates/audioTemplate.html, ArticleTemplates/galleryTemplate.html, ArticleTemplates/galleryTemplateImages.html, ArticleTemplates/videoTemplate.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/55340330-605f4b00-549c-11e9-8e21-fc9ff9bce6a6.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/55340340-648b6880-549c-11e9-9af2-8206a7d21aa6.png" width="300px" />|
=> Resizable text on media pages

ArticleTemplates/assets/scss/pillar/_colour.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/55494789-60de1a00-5633-11e9-8616-a023dfef62ff.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/55494799-66d3fb00-5633-11e9-8b43-e569b7811f83.png" width="300px" />|
=> Only style byline links

ArticleTemplates/articleTemplateBylineImmersive.html
=> Remove by if no byline

ArticleTemplates/articleTemplateContainerImmersive.html, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56289774-a1509400-6119-11e9-908d-5c11a388b4d3.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56289796-aca3bf80-6119-11e9-806c-2c70b54c11a2.png" width="300px" />|
=> Inline immersive bullet points

ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/modules/external/_d2-comment.scss
=> Liveblog question styles

ArticleTemplates/assets/scss/modules/_alerts.scss
=> Center alerts icon

ArticleTemplates/assets/scss/modules/cricket/_match-summary.scss
| --- |  --- |
|<img src="https://user-images.githubusercontent.com/11618797/56367519-4be5b700-61ed-11e9-921e-d51d186163e2.PNG" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/56367536-543df200-61ed-11e9-8c23-d4212427fea4.png" width="300px"/>|
=> Cricket styles typo

ArticleTemplates/assets/scss/modules/galleryImageViewCaption.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/style-sync.scss, ArticleTemplates/galleryImageViewCaption.html
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/56282362-e28b7880-6106-11e9-89fd-0a479a2c604b.png" width="300"/>  | <img src="https://user-images.githubusercontent.com/11618797/56282344-d8697a00-6106-11e9-9d9a-9580b0f08802.png" width="300"/> |
=> New gallery WebView caption

ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56728942-ed1fc080-674b-11e9-9c9a-fbf0fa9529d0.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56728959-fa3caf80-674b-11e9-845f-e3b8f74eb16b.png" width="300px" />|
=> Immersive supporting image caption

ArticleTemplates/assets/scss/modules/galleryImageViewCaption.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/galleryImageViewCaption.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56671388-74b5f280-66ac-11e9-979c-6a9f94a20341.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56734281-468eec00-675a-11e9-90cf-2bbe255951c7.png" width="300px" />|
=> Add gallery credits

ArticleTemplates/assets/scss/modules/content/_main-media.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56811744-562d3400-6831-11e9-8070-1e0c4253363d.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56811777-6fce7b80-6831-11e9-80c9-eed57cbf6dd1.PNG" width="300px" />|
=> Style main media caption links

ArticleTemplates/assets/js/modules/cards.js, ArticleTemplates/assets/js/modules/util.js
=> Remove local storage helpers

ArticleTemplates/assets/scss/modules/external/_element.scss
=> set width on instagram embeds

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/modules/blocks/_comment.scss
Few style tweaks with the new Guardian Sans font.
Also a pullquote fix on photo essay articles on tablets.
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56905313-e1a7fe80-6a97-11e9-8d27-3c94e7f7474b.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56905339-ea003980-6a97-11e9-93cc-78a6e7976432.png" width="300px" />|
=> More new font alignments

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/56958210-90ece000-6b41-11e9-894e-1c438f741a50.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/56958247-a6faa080-6b41-11e9-9951-128315244ace.png" width="300px" />|
=> Set email signup embed height

ArticleTemplates/assets/js/boot.js, package-lock.json, package.json
=> Babel polyfill

ArticleTemplates/assets/scss/modules/_figure.scss, package-lock.json, package.json
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57068876-e4d70080-6cca-11e9-9fd3-e8a1e972dcab.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57068886-ebfe0e80-6cca-11e9-9ef2-2e064c5524c6.png" width="300px" />|
=> Jw video caption font

ArticleTemplates/assets/scss/modules/_commentsHighlighted.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57071413-48186100-6cd2-11e9-831f-03da9f3f6adb.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57071430-52d2f600-6cd2-11e9-89b7-ca522bfbc5c6.png" width="300px" />|
=> Comment pick overflow

ArticleTemplates/assets/scss/modules/galleryImageViewCaption.scss
=> Avoid text size change on orientation change

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57519043-5e49a100-7312-11e9-825e-b5e34eddc21f.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57519064-643f8200-7312-11e9-9999-e913ee66b02d.PNG" width="300px" />|
=> Photo essay caption padding

ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/type/_live.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57523288-82aa7b00-731c-11e9-98d4-19d46863edbe.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57523301-8b9b4c80-731c-11e9-8e48-241df26937c5.PNG" width="300px" />|
=> Liveblog last updated size

ArticleTemplates/assets/scss/modules/charts/_pie-chart.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57541647-67089a00-7347-11e9-8b44-c8a99886d087.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57541659-6cfe7b00-7347-11e9-8fdc-2e3a5ea4fb83.jpg" width="300px" />|
=> Show football possession stats

ArticleTemplates/assets/scss/modules/content/_prose.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57702346-cae7d700-7655-11e9-977b-3b7b0271dff8.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57702356-cf13f480-7655-11e9-8a03-52ec43c9faec.PNG" width="300px" />|
=> Photo essay headers

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/bootstraps/audio.js, ArticleTemplates/assets/js/bootstraps/gallery.js, ArticleTemplates/assets/js/modules/util.js, package-lock.json, package.json, webpack.config.js
=> classList polyfill

ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/modules/_key-events.scss, ArticleTemplates/assets/scss/modules/cricket/_match-summary.scss, ArticleTemplates/assets/scss/type/_article.scss, ArticleTemplates/cricketTemplate.html, ArticleTemplates/footballTemplate.html, ArticleTemplates/footballTemplateLiveblog.html
=> Key events placeholder for football and cricket

ArticleTemplates/assets/scss/modules/_interactive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57922612-07a31080-7898-11e9-8121-0929a1202fef.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57922602-0245c600-7898-11e9-8a1e-2bb341c39429.PNG" width="300px" />|
=> Remove double border on interactives

ArticleTemplates/assets/scss/type/_media-audio.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/57925059-d67a0e80-789e-11e9-83f1-7df22339240e.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/57925073-de39b300-789e-11e9-9f20-1b1340a850b9.png" width="300px" />|
=> Audio title height

ArticleTemplates/assets/scss/modules/_loading.scss, ArticleTemplates/assets/scss/tones/_tone--deadblog.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58028854-74760f00-7b13-11e9-9e97-e753cb39c227.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58028971-953e6480-7b13-11e9-8bb0-86f5970f4a6d.PNG" width="300px" />|
=> Use pillar colour for deadblog links

ArticleTemplates/assets/scss/modules/_figure.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58109139-fbdf8300-7be4-11e9-8b4f-992122a924f9.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58109179-0bf76280-7be5-11e9-8e9f-556d776587f4.PNG" width="300px" />|
=> Match native placeholder backgrounds

ArticleTemplates/assets/js/boot.js, ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/js/bootstraps/campaign.js, ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/js/modules/cards.js, ArticleTemplates/assets/js/modules/more-tags.js, ArticleTemplates/assets/js/modules/quiz.js, ArticleTemplates/assets/js/modules/twitter.js, ArticleTemplates/assets/js/modules/youtube.js, test/spec/unit/modules/ads.test.js, test/spec/unit/modules/youtube.test.js
Reverts guardian/mobile-apps-article-templates#980
=> Revert "Use MutationObserver to notify native layers"

ArticleTemplates/assets/scss/layout/_cricket.scss, ArticleTemplates/cricketTemplate.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58172562-d5772180-7c90-11e9-9a71-d3070610b6f0.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58172587-e58f0100-7c90-11e9-8859-01009990aa9a.PNG" width="300px" />|
=> Remove tab whitespace

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/modules/_figure.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58247612-feabb680-7d51-11e9-825d-3c98ab78eed5.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58247625-023f3d80-7d52-11e9-8672-ce5539844d11.png" width="300px" />|
=> Supporting element caption styles

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/layout/_article--shared.scss, ArticleTemplates/assets/scss/modules/_injectedCreative.scss
=> Photo essay styles

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
=> Handle taller images in photo galleries

ArticleTemplates/assets/scss/modules/external/_element.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58473166-d94aee00-813f-11e9-915e-9530676a5d16.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58473172-dcde7500-813f-11e9-81c0-ffe39e67f452.PNG" width="300px" />|
=> clear tweets next to rich links

ArticleTemplates/assets/scss/modules/_figure.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58546358-13c69080-81fd-11e9-89f7-94009a67dbcb.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58546362-16c18100-81fd-11e9-8e68-d3f289a0a12c.PNG" width="300px" />|
=> Remove side padding on interactive figcaptions

ArticleTemplates/assets/scss/pillar/_sport.scss, ArticleTemplates/cricketTemplateAlert.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58643495-4a80d180-82f7-11e9-9991-63e4af0db236.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58643508-4fde1c00-82f7-11e9-9a5d-a677fa984a2e.png" width="300px" />|
=> Use standard follow icon for cricket games

ArticleTemplates/assets/js/modules/comments.js
=> ESLint fix

ArticleTemplates/assets/scss/layout/_article--shared.scss, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss, ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/58815147-f8092300-861e-11e9-92c4-2c151af9ed43.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/58815156-fb041380-861e-11e9-8954-e9b31393b35b.PNG" width="300px" />|
=> Immersive header fix

ArticleTemplates/assets/scss/helpers/_mixins.scss, ArticleTemplates/assets/scss/layout/_article--photo-essay.scss, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/layout/_base-tone.scss, ArticleTemplates/assets/scss/modules/_sponsorship.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/type/_media-gallery.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59095577-c5a64100-8910-11e9-8198-c24beb6b7e88.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59095727-1a49bc00-8911-11e9-891e-528b169f4751.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/59095748-259ce780-8911-11e9-8e13-3b0e85529c12.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59096442-c7710400-8912-11e9-98a6-606fd5d2255a.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/59096560-02733780-8913-11e9-9097-f64e0ceefc0e.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59096581-1159ea00-8913-11e9-99a1-7ac881cc538f.png" …
=> Consistent bullet mixin

ArticleTemplates/assets/scss/modules/external/_element.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59104388-5e48bb00-8929-11e9-8235-b7e4b3981458.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59104407-6dc80400-8929-11e9-9e96-e971f270b100.PNG" width="300px" />|
=> Reduce iframe width in liveblogs

ArticleTemplates/assets/scss/modules/_interactive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59103045-aa91fc00-8925-11e9-91b8-344b1607c39c.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59103060-b67dbe00-8925-11e9-8689-24354b4f285d.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/59103073-c0072600-8925-11e9-8d18-c69677c745c0.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59103090-c8f7f780-8925-11e9-9827-65707e403420.png" width="300px" />|
=> Remove interactive navbar

ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/external/_element.scss, ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59266105-c60b4880-8c3e-11e9-8f5f-c3380962d06d.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59266159-e76c3480-8c3e-11e9-9513-0ebe3d8eafac.PNG" width="300px" />|
=> Show immersive headers when offline

ArticleTemplates/assets/scss/layout/_article.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59449949-1251b680-8e00-11e9-860f-377b962312c7.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59449970-1da4e200-8e00-11e9-9ccb-062ae50aefd8.PNG" width="300px" />|
=> Add padding to video figcaptions

ArticleTemplates/assets/scss/layout/_football.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59593613-2a6c5300-90ea-11e9-953b-b6577020945b.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59593614-2b04e980-90ea-11e9-9656-d9b9717952d6.PNG" width="300px" />|
=> Remove duplicated standfirst

ArticleTemplates/assets/scss/type/_media-all.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59766130-68f34080-9297-11e9-80ff-e347368fe76a.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59766205-904a0d80-9297-11e9-86fa-118eaf4311e5.png" width="300px" />|
=> Use media background

ArticleTemplates/assets/scss/modules/blocks/_block--live.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59768431-457ec480-929c-11e9-8c67-1ef2cc9f584b.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59768456-516a8680-929c-11e9-949a-2d3ae49244ce.png" width="300px" />|
=> Last updated margin

ArticleTemplates/assets/scss/modules/blocks/_block.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59771811-6fd38080-92a2-11e9-8032-166927a366a0.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59771830-7c57d900-92a2-11e9-97e8-5f32329af5d7.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/59771863-8d084f00-92a2-11e9-9e96-44a9c2a5e412.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59771880-95f92080-92a2-11e9-8200-1369631f88b8.png" width="300px" />|
=> Hide overflowing content

ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/tones/_tone--deadblog.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/59782702-78ce4d00-92b6-11e9-8323-a3148f3ffbf3.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59782711-7c61d400-92b6-11e9-891f-a113387e610d.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/59782729-88e62c80-92b6-11e9-89c8-d8f56c607e16.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/59782747-913e6780-92b6-11e9-8f04-bdbc44e09b2b.png" width="300px" />|
=> Liveblog summary styles

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/modules/youtube.js, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/modules/cricket/_stats.scss
- Updates formstack styles earlier
- Removes " - video" from captions
- Adds affiliate link discalimer styles
- Cricket borders
=> More frequent setupForm checks

ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/60010521-de805780-966f-11e9-8cb7-bf359e3909d6.PNG" width="300px" />| <img src="https://user-images.githubusercontent.com/11618797/60010481-cd374b00-966f-11e9-82b1-bccdc56479e5.PNG" width="300px" /> |
=> multiline series tag

ArticleTemplates/assets/scss/modules/galleryImageViewCaption.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/60099172-0f838980-974f-11e9-8fe4-1b36f3260f07.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60099198-1a3e1e80-974f-11e9-9bc2-0edef83327e1.PNG" width="300px" />|
=> Webview caption credit font

package-lock.json, package.json, webpack.config.js
Avoids function names being minified.
JavaScript increase from 1663kb to 1709kb.
=> keep function names during minification

ArticleTemplates/assets/scss/layout/_article--shared.scss, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/modules/content/_flyers.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss, ArticleTemplates/assets/scss/type/_immersive.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/60036042-2c17b700-96a6-11e9-9344-0d34991f219c.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60036050-31750180-96a6-11e9-808a-1d07584d633c.PNG" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/60036074-3df95a00-96a6-11e9-97de-5d3f337964a3.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60036087-4782c200-96a6-11e9-9e21-8688224fcd68.PNG" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/60036142-6e40f880-96a6-11e9-8363-9019274c6101.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60036166-7a2cba80-96a6-11e9-8a9f-a7cf215636b9.PNG" …
=> Better content grouping

ArticleTemplates/assets/scss/modules/content/_prose.scss
=> Following header padding

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/liveblog.js, ArticleTemplates/assets/scss/modules/blocks/_block--live.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/60671883-093a8f00-9e6c-11e9-86f5-13c06da3934f.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60671882-093a8f00-9e6c-11e9-92b8-65e3c9696e04.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/60671884-093a8f00-9e6c-11e9-8608-314b05a714d5.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/60671885-093a8f00-9e6c-11e9-9d7e-507c1a851854.png" width="300px" />|
=> correctly sized images in liveblogs

ArticleTemplates/assets/scss/modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/61234299-9e6e3b00-a72a-11e9-9f07-1858ec4bb4d8.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61234304-a0d09500-a72a-11e9-967a-c38f272b7171.PNG" width="300px" />|
=> thumbnails without captions

ArticleTemplates/assets/scss/layout/_article--shared.scss, ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss
=> wide figure h2

ArticleTemplates/assets/scss/modules/_advert-slot.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/61372446-09d11d80-a88f-11e9-9545-e5f8a6b2c47b.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61372460-148bb280-a88f-11e9-9b45-c8a3582a3d6b.PNG" width="300px" />|
=> Media page ad slots

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/modules/_quiz.scss, ArticleTemplates/assets/scss/pillar/_colour.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/61473880-4e3be680-a97f-11e9-8c8d-5f4e6314c0da.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61473900-5ac03f00-a97f-11e9-986f-c593e1df0572.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/61473915-64e23d80-a97f-11e9-8803-4584157b0951.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61473935-70356900-a97f-11e9-90a1-cb45dae10e90.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/61473952-788da400-a97f-11e9-90e9-bdb91af59f1a.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61473968-84796600-a97f-11e9-8833-d03dae50df47.png" …
=> Pillar quiz styles

ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/type/_media-all.scss
=> media bullet colour

ArticleTemplates/assets/js/boot.js, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/modules/_advert-slot.scss
Relies on iOS change: https://github.com/guardian/ios-live/pull/4513
| Android | iOS |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/61454945-2c7c3880-a95a-11e9-9432-970d435ea0de.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/61453851-233d9c80-a957-11e9-8535-a229485da5db.png" width="300px" />|
=> ads on gallery pages

ArticleTemplates/assets/scss/helpers/_mixins.scss, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/modules/_bullet.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/type/_media-all.scss
=> Refactor bullet colours

ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/js/modules/util.js
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/62696454-5c09e800-b9d0-11e9-8249-5309e62b5ab6.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/62696471-63c98c80-b9d0-11e9-91b7-b2435a847437.PNG" width="300px" />|
=> Only show ads for non glab galleries

ArticleTemplates/assets/js/bootstraps/campaign.js, ArticleTemplates/assets/js/modules/http.js, ArticleTemplates/assets/scss/modules/_campaign.scss
If the file upload takes 30s, show the error message.
=> add timeout for file uploads

ArticleTemplates/assets/scss/modules/_advert-slot.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/62715676-df3f3400-b9f8-11e9-8cd9-d11b94a3caf6.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/62715701-ea925f80-b9f8-11e9-9921-16bde4f8a2ea.png" width="300px" />|
=> gallery specific ad styles

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/layout/_article.scss
=> Remove old colours

ArticleTemplates/assets/js/modules/http.js
=> add window

ArticleTemplates/assets/js/modules/ads.js, test/spec/unit/modules/ads.test.js
=> Fix Three Failing Tests

ArticleTemplates/assets/scss/layout/_article--liveblog.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/64865847-2b9e1500-d632-11e9-91b3-336fad463a00.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/64865860-348ee680-d632-11e9-9c5e-ec43ec516440.png" width="300px" />|
=> remove sdk caption padding on liveblogs

ArticleTemplates/assets/scss/modules/_campaign.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/64950470-56c37700-d873-11e9-9fcc-7ae221876eec.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/64950469-56c37700-d873-11e9-9038-e319209558a5.jpg" width="300px" />|
=> Correct radio button padding

ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/creativeInjector.js, ArticleTemplates/assets/scss/modules/_injectedCreative.scss, test/spec/unit/bootstraps/liveblog.test.js
Requires iOS and Android changes to be merged at the same time.
=> new inject creative api

ArticleTemplates/assets/scss/modules/_injectedCreative.scss
=> reduce line height for larger creative font

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/twitter.js, ArticleTemplates/assets/scss/modules/_key-events.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, test/spec/unit/modules/twitter.test.js
Reverts guardian/mobile-apps-article-templates#1102
=> Revert "Hide all loading icons when new blocks are inserted"

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/js/modules/twitter.js, ArticleTemplates/assets/scss/modules/_key-events.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, test/spec/unit/modules/twitter.test.js
Merge this when https://github.com/guardian/ios-live/pull/4725 is being merged into master
=> Revert "Revert "Hide all loading icons when new blocks are inserted""

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/scss/themes/darkMode/_darkModeCricket.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/69863944-e1721a80-1295-11ea-9229-86ab534760b1.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/69863959-e8992880-1295-11ea-947c-f85ae9c259c6.png" width="300px" />|
=> set html background colour in dark mode

ArticleTemplates/assets/scss/themes/darkMode/_darkModeMedia.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/70228705-b469b000-174c-11ea-8907-61fd4b2cf6ba.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/70228542-6b196080-174c-11ea-8197-04f9c372a1f9.png" width="300px" />|
=> use darker yellow in dark mode

ArticleTemplates/assets/scss/themes/darkMode/_darkModeArticle.scss
=> dark mode for quiz articles

ArticleTemplates/assets/scss/themes/darkMode/_darkModeMedia.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/70166378-89378000-16bc-11ea-86c3-9db44e905984.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/70166390-90f72480-16bc-11ea-905d-5d7d3a5f35d5.png" width="300px" />|
=> use lighter text and underlining for links

ArticleTemplates/assets/scss/themes/darkMode/_darkModeLiveblog.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/70164768-aa4aa180-16b9-11ea-9747-8002a16fc2ee.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/70164783-b20a4600-16b9-11ea-92fa-05e10f756df5.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/70164798-b9c9ea80-16b9-11ea-8951-02c1e4c20a24.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/70164808-c0f0f880-16b9-11ea-98f8-a11e9e8f4cf4.png" width="300px" />|
=> dark mode liveblog tweaks

ArticleTemplates/assets/scss/modules/_commentsHighlighted.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeComments.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/73841199-fcbb5200-4811-11ea-908e-05ce7b9bd002.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/73841216-03e26000-4812-11ea-9c06-4bc7e8dd3ecb.png" width="300px" />|
=> dark mode comment picks

ArticleTemplates/assets/scss/modules/external/_element.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/73836183-9c72e300-4806-11ea-9e08-2e811a0e5f50.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/73836186-9da41000-4806-11ea-814a-745933eb755e.png" width="300px" />|
=> add dark styles and overflow x for code elements

ArticleTemplates/assets/scss/themes/darkMode/_darkModeArticle.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/74037692-b6ebbe80-49b6-11ea-8cca-aecd5cc53140.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/74037670-a8050c00-49b6-11ea-9c14-7500fb5016e4.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/74037704-be12cc80-49b6-11ea-9852-15ee77be8159.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/74037714-c4a14400-49b6-11ea-91b6-b15db67783d5.png" width="300px" />|
=> audio atom and newsletter signup dark styles

ArticleTemplates/assets/scss/layout/_support.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss, ArticleTemplates/simpleBodyTemplate.html, ArticleTemplates/simpleBodyTemplatePrepopCancelAppleSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelDigipackSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelSubscriptionAndroid.html, ArticleTemplates/simpleBodyTemplatePrepopCredits.html, ArticleTemplates/simpleBodyTemplatePrepopHelpAndroid.html
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/74928666-dd0b5880-53d1-11ea-8875-cb78221cbaf3.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/74928681-e3013980-53d1-11ea-9072-7169bda635be.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/74928701-ebf20b00-53d1-11ea-8670-fa0140280a7a.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/74928719-f44a4600-53d1-11ea-959c-3981bc7f9857.png" width="300px" />|
=> dark mode on settings screens

ArticleTemplates/assets/scss/layout/_support.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/75155427-ef560100-5707-11ea-88f3-8589ffb00df8.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/75155451-fb41c300-5707-11ea-9778-a13756646ddb.png" width="300px" />|
=> links and li item for support dark mode pages

ArticleTemplates/assets/scss/themes/darkMode/_darkModeSpecialReport.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/76957464-c17e6980-690d-11ea-8ed7-0d25785b57e0.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/76957518-d78c2a00-690d-11ea-9741-89ea5f129e5c.png" width="300px" />|
=> lighter kicker colour

ArticleTemplates/assets/scss/themes/darkMode/_darkModeFootball.scss
| --- | --- |
|![Simulator Screen Shot - iPhone 11 Pro - 2020-03-24 at 12 59 36](https://user-images.githubusercontent.com/53435954/77428061-6518bf80-6dcf-11ea-82b9-e5817a475936.png)|![Simulator Screen Shot - iPhone 11 Pro - 2020-03-25 at 08 02 39](https://user-images.githubusercontent.com/53435954/77514569-073bb480-6e6f-11ea-875e-35f6749b030e.png)|
=> GLA-1921-Update-article-football-tables-for-darkmode

ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/layout/_article--visual.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeGuardianLabs.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/77915527-8f66f300-728f-11ea-98cf-ae01f2037c2c.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77915580-a1e12c80-728f-11ea-88a3-8244dba95198.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/77915623-b4f3fc80-728f-11ea-86bc-e3459a632672.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77915664-c3421880-728f-11ea-8c2b-86a8de990161.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/77915700-d0f79e00-728f-11ea-9b15-8947af4fb6fb.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77915743-e2d94100-728f-11ea-99c3-fc0fd465c5de.png" …
=> glab dark mode fixes

package-lock.json
`npm audit` reported some issues.
- Ran `npm audit fix` to patch issues; `package-lock.json` updated
=> NPM Audit Fix - 3/4/2020

package-lock.json, package.json
Snyk reported an issue, this is the fix.
- Upgraded `webpack-cli`
=> Upgrade webpack-cli

package-lock.json, package.json
=> Bump Webpack To Latest

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeGuardianLabs.scss, ArticleTemplates/assets/scss/type/_guardianlabs.scss, ArticleTemplates/assets/scss/type/_media-gallery.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/79319051-bcf2a400-7eff-11ea-9690-bf2b696a1a96.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/79319867-ce887b80-7f00-11ea-9a8f-c8ed1f478754.png" width="300px" />|
TODO (iOS and Android PRs):
- Use immersive templates for `photoEssay` and `immersive` glab articles
- Use glabs green for play icon on videos
=> use white background for guardian labs

ArticleTemplates/assets/scss/base/_colour.scss
I must have changed this in the last PR. Updated to the colour in Figma.
=> Use correct Guardian Labs colour

ArticleTemplates/assets/scss/modules/content/_standfirst.scss
=> revert 600px wide standfirsts

ArticleTemplates/assets/scss/tones/_tone--deadblog.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/81065966-4b8d8c00-8ed4-11ea-95c3-bb092432a648.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/81065994-5516f400-8ed4-11ea-8ce9-025414b78a17.png" width="300px" />|
=> keep pillar colours on links

ArticleTemplates/assets/scss/helpers/_mixins.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeImmersive.scss, ArticleTemplates/assets/scss/type/_immersive.scss
- Removes border above first dropcap
- Increases font weight for dropcap
- Update border colour
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/81684389-d4fe0a80-944e-11ea-979e-d8e7ef4474d5.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/81684427-ddeedc00-944e-11ea-9842-02a9aa50a4b2.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/81684476-e810da80-944e-11ea-9e36-0ce7a75da138.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/81684529-f3fc9c80-944e-11ea-8ec5-05ce556c52bf.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/81687406-ee07bb00-9450-11ea-84cb-be9f05e903f9.png" width="300px" />|<img …
=> Dropcap weight update

ArticleTemplates/assets/js/boot.js, ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss, test/spec/unit/bootstraps/boot.test.js
Can be set using by updating `__TEST_SPEC__` on `articleTemplate.html`
```
"tests": "{
hideAdsTest: 0
}"
```
| id | test |
| --- | --- |
| 0 | normal/control |
| 1 | different text |
| 2 | yellow banner |
| Light | Dark |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/82209924-0b7fcd80-9906-11ea-9025-f3205cf85446.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/82209949-15093580-9906-11ea-835a-89e73993d25d.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/82209975-20f4f780-9906-11ea-9246-b70b796ebbfd.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/82210007-2a7e5f80-9906-11ea-8a87-71b38f02c749.png" width="300px" />|
|<img …
=> hide advert variants

ArticleTemplates/liveblogTemplateLivePromo.html
=> update title copy in try live card

package-lock.json, package.json
Keeping dependencies up-to-date.
- Bumped webpack to v4.44.1
- Bumped terser-webpack-plugin to v2.3.8
=> Bump Webpack And terser-webpack-plugin

ArticleTemplates/assets/scss/layout/_article.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/90761710-b922c400-e2db-11ea-8d8a-dd6da6cd0e3f.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/90761749-c5a71c80-e2db-11ea-93a9-28cd4448456e.png" width="300px" />|
=> center standfirst

package-lock.json, package.json
I can't see it being used anywhere.
- Removed `image-webpack-loader` as a dependency
=> Remove image-webpack-loader

README.md
=> Update labs example

ArticleTemplates/assets/js/modules/premiumTaster.js, ArticleTemplates/assets/scss/modules/_premium-taster.scss
This is offline premium taster indicator that builds on top of [PR](https://github.com/guardian/mobile-apps-article-templates/pull/1267) 
| Light | Dark|
| --- | --- |
|<img width="200" src="https://user-images.githubusercontent.com/12860328/98280156-e144c980-1f92-11eb-860d-f2e90fafd1df.png">|<img width="200" src="https://user-images.githubusercontent.com/12860328/98280201-f4579980-1f92-11eb-8ba9-09f05c1bba11.png">|
=> LIVE-1092: Offline premium taster

ArticleTemplates/assets/scss/themes/darkMode/_darkModeOpinion.scss
This is a rare article combination that was released last week. Add the classnames to support dark mode styles.
https://www.theguardian.com/commentisfree/2020/nov/07/i-know-how-ill-get-through-this-winter-oversized-jumpers-and-triple-jacket-potatoes
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/99258507-93d91f80-2810-11eb-8d41-a1e556fabe0a.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/99258528-9cc9f100-2810-11eb-91bd-b3784c469bce.png" width="300px" />|
=> opinion feature article dark mode styles

ArticleTemplates/assets/scss/modules/_cutout.scss
=> increase z index of cutout

package-lock.json, package.json
Keeps dependencies up to date.
- Bumped versions of Jest, Babel-Jest and Webpack
=> Bump Jest, Babel-Jest And Webpack

ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/modules/_advert-slot.scss
We'd like to put square ads in the first ad slot.
- Made the first ad slot on the page square
=> Square First Ad Slots

ArticleTemplates/assets/js/bootstraps/campaign.js
This PR adds page if to the submission if there's any hidden field in the form. It was tested in debug app.
This change needs to be released after this MAPI PR https://github.com/guardian/mobile-apps-api/pull/2410
=> Add page id to callout submission
