guardian/mobile-apps-article-templates

ArticleTemplates/footballTemplateLiveblog.html
It is never set in the app and is showing up as is on football liveblogs.
=> Remove the unused __SUMMARY__ tag from the football liveblog template

Gruntfile.js
This patch makes the build stdout to be saved to a .log in each
projects root folder. Errors will still be printed in the console.
It also prints a "Building app" message to show it's doing something.
The main reasoning behind this is to silence the iOS output, as it's
especially verbose and makes it complicated to understand what grunt
is actually doing.
=> Replace build output with a simple build message

README.md
The android build will fail without it.
=> Add `--card` option to `grunt installer`

Gruntfile.js
If there's a syntax error in `config.js`, an empty configuration will
be assumed and "Config module not found" will be printed to the
console.
This patch changes the message to a more generic "failed to load"
explanation and prints out the exception for full detail. This
hopefully makes syntax errors more obvious and easier to find.
=> Change message for require('./config') failure

package.json
The smooth-scroll package defined in package.json was changed in commit 10e4672e8e061937cda3945b335dc232f7888882 from using a github url to a version number.
Version numbers can only be used for packages that exist in NPM. Smooth-scroll doesn't, so npm install fails to find the package.
This needs to be changed back to a git url.
=> GIA-3854: Specify git address for smooth-scroll

test/server.js
The static html files in `test/fixture/` were changed from accessing
assets via /root to accessing them using relative paths.
<link rel="stylesheet" type="text/css" media="all" href="/root/ArticleTemplates/assets/css/style-sync.css">
<link rel="stylesheet" type="text/css" media="all" href="../../ArticleTemplates/assets/css/style-sync.css">
That change made the html files render properly if you manually open
them in a browser. That change also made the files not render if
accessed by localhost:3000/file.html.
This change exposes the whole source tree in the root of the express
server. This is a bit overkill, but it makes localhost:3000/file.html
render properly.
As a side effect, this also fixes wraith.
=> Make static files served by express render properly

Gruntfile.js
This is templates-side bit of work from what David started on the android side.
David's pull request is https://github.com/guardian/android-news-app/pull/2441 . The new "Templates (development mode)" debug option needs to be on for this to work!
`grunt deploy` will build and deploy the templates to the device, and force an article reload
Here's an extra trick I added
`grunt shell:clean` clears all the generated files : -)
=> Better workflow

ArticleTemplates/cricketTemplate.html
If __IS_LIVE__ replaced by native layer then the timestamps on a cricket live blog will be reformatted using relativeDates module.
=> Add is live flag to cricket template

ArticleTemplates/articleTemplateContainerComment.html, test/fixture/article-tone-comment.html
Currently the cutout sits in front of the byline on opinion articles. This makes it impossible to tap the author's byline and navigate to their author page.
This change moves the cutout behind the byline, allowing the user to tap the byline.
=> Move byline in front of cutout

ArticleTemplates/articleTemplateTag.html
Tags can link to lists or fronts in the native apps. However the href in articleTemplateTag.html has 'link' hardcoded in the path, meaning tags which should link to fronts don't  go anywhere right now.
This updates articleTemplateTag.html to replace the hardcoded 'link' with a placeholder __TAG_TYPE__. The native layers will replace this with 'link' or 'front' depending on the tag, and the tag should then work correctly!
=> replace ‘list’ in template with placeholder __TAG_TYPE__

ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/js/modules/creativeInjector.js, ArticleTemplates/liveblogTemplateContributionsEpic.html, test/spec/unit/modules/adsTest.js
This PR: 
* Changes the name of the class to not conflict with a same already in the markup submitted by the contributions team
* If there is a contributions epic after a liveblog block which an ad should go, the ad should instead go after the next liveblog block.
=> Ads and epics shouldn't be inserted after the same block

circle.sh
Annoyingly, there is a merge conflict in the CI that I can't replicate locally.  
This should just force the release branch to be the same state as master.
Are you okay with this @GHaberis ?
=> need to force the `merge`

ArticleTemplates/assets/scss/layout/_article--immersive.scss
Text ought to wrap around portrait-oriented supporting images.
=> Fixup portrait supporting images on tablet

README.md, package.json
Occasionally, IOS or Android devs might want to develop against a branch that hasn't made it into `release` yet.
this adds instructions to the readme on how they might do that
=> Updating readme for IOS and Android devs

circle.sh
Unfortunately I didn't realise that the apps release was depending on a particular git commit hash, so this stops the commits from being overwritten.
Sanity check @GHaberis ?
=> Go back to merging, not reseting

ArticleTemplates/articleTemplate.html
data-content-section on the body tag was using single quotes, section names can contain unescaped apostrophes, if they do this breaks the template. Wrapping the section name in double quotes guards against this.
=> use double quotes to wrap data-content-section

circle.sh
On the CI env we merge master into release, we should always take the changes from master over release if/when we have conflicts.
=> CI merge conflict fix

ArticleTemplates/assets/js/modules/messenger.js, Gruntfile.js
jshint was throwing a warning saying the global 'Promise' wasn't defined, even though the global comment at the top of messenger.js was present. 
This is because '-Promise' was listed in the predef (pre-defined) option list, the '-' prefix removed Promise from the list of predefined variables and caused this issue. 
Promise no longer belongs is in this predef list so I've removed it which fixes the issue.
=> Fix jshint warning

ArticleTemplates/liveblogTemplateContributionsEpic.html
This comment is causing problems in the liveblog template as it isn't a valid CSS comment.
It had the consequence of ignoring the first CSS class of the CSS blob.
A workaround is in place by pre-pending a dummy CSSS class in the CSS blob, but this should fix it long term wise.
cc @Leyths
=> Fix comment breakage.

ArticleTemplates/assets/scss/helpers/_mixins.scss
There is an [interesting feature of iOS Safari](https://stackoverflow.com/questions/3226001/some-font-sizes-rendered-larger-on-safari-iphone) that resizes text if the browser feels the font size will be too small.
This is causing the timestamp and author follow link text to appear larger than expected in iOS 10.3
I have fixed this by applying the property `-webkit-text-size-adjust: none;` to the `meta` mixin.
Before:
After:
=> Fix meta font size

Gruntfile.js, circle.yml, package.json
I have experienced some frustration with the way the build, testing and validation tasks are tightly coupled within the Gruntfile. It means the developer has to wait for tests and validation to pass when they run `yarn develop`.
I have extracted validation and testing into their own Grunt tasks. These are still executed as part of the watch task when code is changed, but are not executed when the task is first started. The `rsync` task will also be called when `yarn develop` is first started.
The fact that I didn't need to change the README as part of this change indicates that perhaps this is the way it ought to be working anyway.
This level of task granularity gives us a greater flexibility over when tasks are run, allowing us to develop more efficiently.
=> Extract validation and test tasks

.npmignore
When installing mobile-apps-article-templates npm package I found no assets were included in the modules directory. This is because our .npmignore file wasn't working as expected. I've updated and tested (using this https://www.npmjs.com/package/irish-pub) and these changes should mean we only publish the files required by the native app.
=> Only publish required assets to NPM

ArticleTemplates/assets/scss/layout/_article--immersive.scss
This increases line-height in immersive headlines, and tightens spacing around the headline so the header doesn't take as much space.
=> Stop letters from touching in immersive template

ArticleTemplates/simpleBodyTemplatePrepopCancelSubscriptionAndroid.html
Goes with this PR: https://github.com/guardian/android-news-app/pull/3873
Adds a simple new "cancel a subscription" page. I copied the "simple...Help.html" template and changed the words.
=> Cancel a subscription page (AND-11756)

Gruntfile.js, README.md, config.sample.js, docs/how-to-deploy.md
The mobile-apps-article-templates NPM package is now used by the ios-live repo. These changes update the docs to reflect this change.
=> update docs to reflect changes to iOS releases

circle.sh, package.json
Now that the templates are being published to NPM, there is no need for a release branch.
This change removes commits to the release branch from the CI process.
Automated version bumps to `package.json` will be committed directly to master.
=> Sunset release branch

ArticleTemplates/assets/scss/layout/_article--immersive.scss
If an immersive article header contains an iframe, the iframe does not stretch to fit the full width of the viewport, leaving a black space to the right. 
A temporary fix has been implemented in this specific article, whereby the width is added by asynchronously loaded JavaScript, resulting in a FOUC. 
This change implements a more permanent fix to this display issue.
=> Make iframes in immersive articles 100% width

circle.sh
Currently publishing the update to the android-news-app is failing because the `package.json` is in the `android-news-app` subdirectory, not the root directory of the repo.
This change checks for the `package.json` in the correct directory of the android-news-app repo.
=> Circle CI: cd into correct dir for Android App

ArticleTemplates/assets/js/modules/ads.js
An issues was reported with the Guardian App when it is used with a more recent version of Android WebView (based on Chrome 61).
In Chromium/Chrome (the web rendering engine) the scrolling element in HTML documents has been moved to be the `documentElement` instead of `document.body`. The ad was incorrectly placed in the page because it is using `document.body.scrollTop` to read the current scroll position.
Switching the references to `document.body.scrollTop` to use `document.scrollingElement.scrollTop` fixes the issue. 
The `document.scrollingElement.scrollTop` property acts as an alias for either `document.documentElement` or `document.body`, depending on which one will reflect the full page's scroll offset on its scrollTop property.
=> Fix issue with ad position on Webviews using Chromium 61+

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/modules/twitter.js, ArticleTemplates/audioTemplate.html, ArticleTemplates/commentsTemplate.html, ArticleTemplates/cricketTemplate.html, ArticleTemplates/errorExpiredContent.html, ArticleTemplates/footballTemplate.html, ArticleTemplates/galleryTemplate.html, ArticleTemplates/interactiveTemplate.html, ArticleTemplates/liveblogTemplate.html, ArticleTemplates/videoTemplate.html
Don't enhance tweets if the native later has replace the placeholder __DISABLE_ENHANCED_TWEETS__ with `true`.
=> Add disable tweet enhancement switch

ArticleTemplates/assets/js/bootstraps/common.js
The Meta container was being removed on paid for content in the app even when there was a byline.
This was happening because the logic didn't take into account that  `bylineElems[0].children.length` could be 0 even if there was text content within `bylineElems[0]`. The original logic was written to accommodate bylines wrapped in anchor tags that linked to the author profile, however not all are wrapped in anchor tags.
I've updated the check to `bylineElem.innerHTML === ""` which fixes the issue.
I've also simplified this logic, as the only tone ever present on paid for content is `tone-news` so the a big chunk of the previous logic was totally redundant.
Before...
After...
=> Fix issue with byline being hidden in paid for articles

ArticleTemplates/assets/js/modules/youtube.js
The youtube.js module imports a dependency `util.js`, all utility calls should call methods on this import, rather than using the previous `GU.util` object on the window.
=> Use imported module 'util' instead of 'GU.util'

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/article.js, ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/modules/atoms/services.js, ArticleTemplates/assets/js/modules/services/impl/viewport-io.js, ArticleTemplates/assets/js/modules/services/impl/viewport-scroll.js, ArticleTemplates/assets/js/modules/services/viewport.js
This is to insert the CSS and JS necessary for atoms to run properly. CSS is straightforward. For JS, it is trickier. We need a reference to the generated JS, as each atom will expose a factory module. To avoid polluting the global scope, atoms will be assigned to the `this` object (each JS bundle will be of the form `this.<atom type> = <expression returning a module>`), which we can define by wrapping the generated code inside a function and call that function using `Function.prototype.call`, passing an object to serve as a repository.
TODO:
=> Rendering atoms using the library

circle.yml, package.json
Turns out we've been using the wrong node version all along?
=> Specify node version in circle.yml

ArticleTemplates/simpleBodyTemplatePrepopHelp.html
As per https://theguardian.atlassian.net/browse/GLA-275, I've removed all references to the price from the FAQs. I've also taken the opportunity to rename 'alerts' to 'notifications' (which we changed a while ago in the app).
=> Update app FAQs

ArticleTemplates/assets/js/modules/services/impl/viewport-io.js
Whenever multiple snippets are in the page and each registers a viewport observer at the same threshold, they may all fire when the first element crosses its threshold. This fix makes sure only the callbacks corresponding to the element targeted by the intersection are called.
=> Fix: Account for multiple elements on the same threshold

ArticleTemplates/assets/js/modules/atoms/services.js
Off the [fix](https://github.com/guardian/atom-renderer/releases/tag/v0.8.16) we released yesterday, we need to make sure the apps still receive data in the form it is expecting. This should be temporary until both apps are updated to handle strings instead of numbers, but that would delay the release for another few weeks.
It's working as expected:
=> Translate enum strings to enum numbers

ArticleTemplates/assets/js/modules/atoms/services.js
Makes sure special characters such as `?` are properly encoded before inserting into the DOM.
=> Encode JSON as a URI component

ArticleTemplates/assets/js/modules/quiz.js
The mobile apps have been showing users the quiz result message that corresponds to `score`**`- 1`**. For instance, on this quiz:
* https://www.theguardian.com/uk/quiz/2013/jan/27/british-citizenship-test-quiz-new
...if you complete the quiz with a score of 8 out of 10 correct answers, you get the right score displayed (_"You scored: 8/10"_), but the message shown is the message for 7/10, which includes the phrase _"...on this 10-question test you've come in at **70%**..."_ and exposes the problem:
We've had this off-by-one error since the functionality to show the result text was initially added with 102c32bfc, and [a few other users spotted it](https://twitter.com/Open_Book/status/775340704637788160), but obviously it only affects quizzes displaying on the mobile apps (iOS and Android), …
=> Fix unduly harsh quiz result messages

ArticleTemplates/assets/scss/garnett-modules/_hide-garnett.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/modules/_show-garnett.scss, ArticleTemplates/assets/scss/style-sync.scss
Garnett set-up CSS to show/hide HTML blocks without affecting the current templates.
Anything with the class `show-garnett` will show up on garnett, but be hidden with `display: none` on the current templates. Conversely, anything with the class `show-garnett` will show only on garnett, and not on the currently active templates.
=> Show and hide elements for new templates

ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss, ArticleTemplates/assets/scss/garnett-layout/_article--audio.scss, ArticleTemplates/assets/scss/garnett-layout/_article--comment.scss, ArticleTemplates/assets/scss/garnett-layout/_article--immersive.scss, ArticleTemplates/assets/scss/garnett-layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/garnett-layout/_base-tone.scss, ArticleTemplates/assets/scss/garnett-modules/_cutout.scss, ArticleTemplates/assets/scss/garnett-modules/blocks/_block--live.scss, ArticleTemplates/assets/scss/garnett-modules/content/_prose.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-style-async.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/garnett-type/_media-all.scss, ArticleTemplates/assets/scss/garnett-type/_media-audio.scss, ArticleTemplates/assets/scss/garnett-type/_media-video.scss
This tries to fix an assortment of visual issues with the templates — mostly caused by my previous PRs…
Among the issues fixed:
- Stops headline and author cutouts from overlapping
- Removes old blue from quotemarks
- Shows the full standfirst in audio articles
- Removes a white stripe next to standfirst in audio articles
- Changes the way the link underline is implemented so liveblog links are readable
- Adds padding around metadata in video articles
- Separates bullet points and text a little more
- Aligns immersive dropcap (need to bring dropcap back to feature articles)
=> Layout fixes

ArticleTemplates/assets/scss/garnett-modules/_alerts.scss, ArticleTemplates/assets/scss/garnett-modules/_avatar.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss
This moves the author byline icon circle to the right, so all the text is left-aligned, and adds pillar colour to the icon background.
=> Move author icon to the right

ArticleTemplates/assets/scss/garnett-layout/_article--audio.scss, ArticleTemplates/assets/scss/garnett-layout/_article.scss, ArticleTemplates/assets/scss/garnett-layout/_base-tone.scss, ArticleTemplates/assets/scss/garnett-modules/_figure.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-modules/content/_prose.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-type/_comment.scss, ArticleTemplates/assets/scss/garnett-type/_media-all.scss, ArticleTemplates/assets/scss/garnett-type/_media-audio.scss
This adds the garnett 4 line styles to all templates — and 8 lines to comment articles.
=> Headline & Meta cleanup

ArticleTemplates/assets/scss/garnett-layout/_article--audio.scss, ArticleTemplates/assets/scss/garnett-layout/_article.scss, ArticleTemplates/assets/scss/garnett-layout/_base-tone.scss, ArticleTemplates/assets/scss/garnett-modules/_figure.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-modules/content/_prose.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-type/_comment.scss, ArticleTemplates/assets/scss/garnett-type/_media-all.scss, ArticleTemplates/assets/scss/garnett-type/_media-audio.scss
Builds on #702 to style main media captions with a circular icon instead of a square
=> Feature main media captions

ArticleTemplates/commentsTemplate.html, ArticleTemplates/commentsTemplatePreview.html, ArticleTemplates/footballFixturesTemplate.html, ArticleTemplates/simpleBodyTemplate.html, ArticleTemplates/simpleBodyTemplatePrepopCancelAppleSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelDigipackSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelSubscriptionAndroid.html, ArticleTemplates/simpleBodyTemplatePrepopCredits.html, test/garnett-fixture/comments.html
The comments template needs the 'async' styles added as a `<link>`, this `<link>` was accidentally removed as part of this PR https://github.com/guardian/mobile-apps-article-templates/pull/686. 
This PR adds the `<link>` back into the head of `commentsTemplate.html`, using the placeholder `__ASYNC_STYLES__` for the filename.
It also updates a number of other HTML templates to use the placeholder `__ASYNC_STYLES__`.
=> Fix comments bug

ArticleTemplates/assets/scss/garnett-modules/_advert-slot.scss, ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss, test/fixture/article-tone-news.html
Ads on tablet layouts are positioned to the top/right of the article body in the app templates. A placeholder reserves the space for the ad. This placeholder was mispositioned on iPad layouts causing the paragraph text to overlap the placeholder after this commit: https://github.com/guardian/mobile-apps-article-templates/commit/c78bef993d6da842ba90b03022344df9f5b80c0d#diff-6394f01c0d5259cee98d42521387e67d
This PR fixes the position.
**Before...**
**After...**
=> Ad position fix

ArticleTemplates/assets/scss/base/_typography.scss, ArticleTemplates/assets/scss/garnett-base/_typography.scss, ArticleTemplates/assets/scss/helpers/_variables.scss
We're no longer using the `agaate` font files. This PR update the app's templates to use the correct file names.
=> update fonts to use correct headline font filename

ArticleTemplates/assets/scss/garnett-pillar/_arts.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_lifestyle.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-pillar/_sport.scss
Updates the colour palette variable values without renaming them, and adds a note about variable naming differences between MAPI and app templates.
=> Update colour palette

ArticleTemplates/assets/scss/garnett-type/_immersive.scss
Removes a white background from immersive headlines that was making them unreadable.
=> Fixes unreadable immersive headlines on large tablet

ArticleTemplates/articleTemplateContainer.html, ArticleTemplates/articleTemplateContainerComment.html, ArticleTemplates/assets/scss/garnett-layout/_article.scss, ArticleTemplates/assets/scss/garnett-modules/content/_main-media.scss, ArticleTemplates/assets/scss/garnett-modules/content/_standfirst.scss, test/garnett-fixture/analysis-news-specialreport.html, test/garnett-fixture/analysis-news-video.html, test/garnett-fixture/analysis-news.html, test/garnett-fixture/analysis-opinion.html, test/garnett-fixture/article-arts.html, test/garnett-fixture/article-lifestyle.html, test/garnett-fixture/article-news-specialreport.html, test/garnett-fixture/article-news.html, test/garnett-fixture/article-sport.html, test/garnett-fixture/comment-arts.html, test/garnett-fixture/comment-lifestyle.html, test/garnett-fixture/comment-news.html, test/garnett-fixture/comment-opinion-multipleauthors.html, test/garnett-fixture/comment-opinion-nocutout.html, test/garnett-fixture/comment-opinion.html, test/garnett-fixture/comment-sport.html, test/garnett-fixture/guardianview-opinion.html, test/garnett-fixture/recipe-lifestyle.html, test/garnett-fixture/review-opinion.html
This uses the feature style `main-media--hidden-caption` on article and comment templates.
**Before**
**After**
=> Update main media caption styles

ArticleTemplates/assets/scss/garnett-modules/content/_standfirst.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
Bold was set to font-weight: 400, which is now the default font weight, so this fixes that right up.
=> Bold in standfirsts

ArticleTemplates/articleTemplateContainerComment.html, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-type/_comment.scss, test/garnett-fixture/comment-arts.html, test/garnett-fixture/comment-lifestyle.html, test/garnett-fixture/comment-news.html, test/garnett-fixture/comment-opinion-nocutout.html, test/garnett-fixture/comment-opinion.html, test/garnett-fixture/comment-sport.html
* moves timestamp above the alerts button in comment articles
* tidies up comment fixtures to reflect this and some past changes
* makes the comment headline light, and colours the byline even when there's no link
* tidies up comment count alignment
=> Comment headline & meta tweaks

ArticleTemplates/assets/js/bootstraps/audio.js
On Android the template needs to inform the native layer that a horizontal swipe has begun/ended, the Android layer will ignore horizontal swiping when this occurs, meaning users can use the slider on Audio templates. `GuardianJSInterface.registerRelatedCardsTouch` is the interface the JS can call to do this.
=> Handle Horizontal Swipe on Audio slider

ArticleTemplates/assets/scss/garnett-pillar/_opinion.scss, ArticleTemplates/assets/scss/garnett-type/_comment.scss
This adds a light salmon background to opinion articles — not just comment, everything except media
**Before**
**After**
=> Add background to opinion articles

ArticleTemplates/assets/js/bootstraps/audio.js
I reverted this PR https://github.com/guardian/mobile-apps-article-templates/pull/741 because the `registerRelatedCardsTouch` calls were fired when swiping on the `document` which was too general. They should only be fired on swiping use the `MobileRangeSlider`.
The `MobileRangeSlider` (3rd party lib) doesn't provide a nice API for passing callbacks on scroll start and scroll end, however the prototype has the functions 'start' & 'end'. 
I've overridden these functions on the prototype so they retain their existing behaviour but also call `registerRelatedCardsTouch`. We were already doing this for `MobileRangeSlider.prototype.end`.
=> Handle Horizontal Swipe on Audio slider: Take 2

ArticleTemplates/assets/scss/garnett-layout/_article.scss, ArticleTemplates/assets/scss/garnett-modules/content/_headline.scss
Headlines should now default to font-weight 500 (Regular) instead of the old 600 (Semibold)
=> Headline weight

ArticleTemplates/assets/scss/layout/_article--liveblog.scss
This adds 3px space above liveblog headlines, when there is no series tag. These were previously displaying too close to the native interface at the top
Note: this change is in lines 22–25…
The rest of the changes are just VS Code being super tidy about white space
=> Liveblog headline spacing

ArticleTemplates/assets/scss/garnett-layout/_article.scss
My bottom is causing a white gap at the bottom of all articles.
=> Removed bottom margin

ArticleTemplates/assets/scss/garnett-type/_guardianview.scss, test/garnett-fixture/guardianview-opinion.html
Multi-rule was overlapping meta on Guardian view template.
=> Removed negative margin & updated fixture

ArticleTemplates/assets/scss/garnett-layout/_article--comment.scss, ArticleTemplates/assets/scss/garnett-layout/_base-tone.scss, ArticleTemplates/assets/scss/garnett-modules/_cutout.scss
As the big hairy cat person* illustrates here: under some circumstances the byline/headline can overlay the byline cutout.
*All byline cutouts combined
=> Byline img overlap

ArticleTemplates/assets/scss/garnett-modules/external/_element.scss
Removes white gap under main media video atoms
**Before**
**After**
=> Removes white space under main media video

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-type/_live.scss
This changes the headline background, on liveblogs, a to kicker-colour. It also updates some shades in the news pillar. Has a lot of code to get tablet to work :/
Phone — before
Phone — after
Tablet — before
Tablet — after
=> Liveblog background

ArticleTemplates/assets/scss/garnett-modules/content/_standfirst.scss
Currently, the last link in the standfirst is set to `inline-block`. This pushes proceeding text down onto this next line
This change makes the standfirst inline again.
**before**
**after**
I believe the standfirst was being set to `inline-block` in order to add bottom margin if and only if _the link is at the very end of the standfirst_. However, this selector is targeting _the last link in the standfirst_, regardless of its location within the standfirst.
I'm not sure if there is a selector that can achieve the original purpose. @duarte let me know if you are happy to lose this bottom margin, or if we need to come up with an alternative.
**With margin (before this change)**
**Without margin (after this change)**
=> Inline links in standfirst

ArticleTemplates/assets/scss/garnett-style-sync.scss, ArticleTemplates/assets/scss/garnett-type/_collection.scss, ArticleTemplates/collectionBlockTemplate.html, ArticleTemplates/collectionTemplate.html
This PR adds two new templates the apps can use to render a new type of content which we're calling a "collection". This will eventually look something like the design below provided by @blongden73. The image at the top and title are native, everything below is rendered using these HTML templates.
Not shown below are the "Read full article ->" links that should appear at the end of each "block", I have put those in the template though.
`collectionsTemplate.html` is a copy of `interactiveTemplate.html` but with the `interactives.css` swapped for the CSS used in `articleTemplate.html`.
I will need to add to the CSS later, but I wanted to open this PR now to try and get feedback on the general direction, if possible?
=> Add new templates for collections (AA-14)

ArticleTemplates/assets/scss/garnett-type/_collection.scss, ArticleTemplates/collectionBlockTemplate.html, ArticleTemplates/collectionTemplate.html
* Overrides the colour of the "Read full article" links.
* Adds a lot of space at the bottom.
=> Collections tweaks 1

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_arts.scss, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-pillar/_lifestyle.scss, ArticleTemplates/assets/scss/garnett-pillar/_news.scss, ArticleTemplates/assets/scss/garnett-pillar/_opinion.scss, ArticleTemplates/assets/scss/garnett-pillar/_sport.scss, ArticleTemplates/assets/scss/garnett-type/_media-all.scss
No visual changes (🤞) just better organisation of the pillar colours file.
This stops using local variables in each pillar file, moving pillar colours to the global colour variables file. Now pillar colours can be used anywhere! Also moves the code to make media backgrounds black in all pillars from pillar colour file to the media-all file.
=> Colour sorting

ArticleTemplates/assets/js/modules/immersive.js, ArticleTemplates/assets/scss/garnett-pillar/_colour.scss, ArticleTemplates/assets/scss/garnett-tones/_tone--special.scss, test/garnett-fixture/immersive-news-special.html
Adds styles for special report immersives.
Note: I have removed a line of JS from `ArticleTemplates/assets/js/modules/immersive.js`, and I don't understand why it was there in the first place — this needs to be tested on device and might need some work before release!
=> Special report immersive

ArticleTemplates/assets/scss/garnett-modules/_keyline.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, ArticleTemplates/assets/scss/garnett-type/_media-all.scss
Moves the comment separator line up a little. Makes the line colour match `keyline` colour on media. Tidies up padding a little.
**Before**
**After**
=> Comment separator line is good now

ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/garnett-layout/_base-tone.scss, ArticleTemplates/assets/scss/garnett-modules/_key-events.scss, ArticleTemplates/assets/scss/garnett-modules/_tags.scss, ArticleTemplates/assets/scss/garnett-tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/garnett-tones/_tone--special.scss, ArticleTemplates/assets/scss/garnett-type/_live.scss, ArticleTemplates/assets/scss/modules/_key-events.scss, ArticleTemplates/assets/scss/modules/_tags.scss, ArticleTemplates/assets/scss/tones/_tone--comment.scss, ArticleTemplates/assets/scss/tones/_tone--deadblog.scss, ArticleTemplates/assets/scss/tones/_tone--live.scss
With the special report page background becoming a little darker, tag button backgrounds became hard to see. This restores their visibility.
This PR also removes some tag-specific colour vairables that shouldn't be necessary anymore
=> Tags in special reports

ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss
=> Softer link underlines

ArticleTemplates/assets/scss/garnett-type/_live.scss
Adds some padding below the liveblog standfirst, and changes the typeface to text egyptian
**Before**
**After**
=> Liveblog standfirst spacing & typeface

ArticleTemplates/assets/scss/garnett-pillar/_colour.scss
Fixes link highlighting bug in templates.
Occasionally standfirsts come in from MAPI without a `<p>` tag wrapper. When this happened, links were not getting underlines — and now they will.
=> The lost PR: highlight all links in standfirsts

ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/scss/garnett-layout/_article--shared.scss, test/fixtures/comment-opinion-interactive.html
`.element-interactive` emdeds in articles were wider than the width of the viewport on larger devices (eg. iPad), resulting in the lefthand side of the immersive being partially hidden.
An example can be seen in the bug report: https://trello.com/c/R11K2GIS/28-apps-garnett-related-article-embed-bug
This was caused by a `width` being set on these elements in `_article--shared.scss`. Removing this width means the`.element-interactive` inherits the style `width:auto`.
Fixed example...
=> fix element-interactive embed bug

ArticleTemplates/assets/js/modules/youtube.js, ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss, ArticleTemplates/assets/scss/garnett-modules/content/_meta.scss, test/fixtures/article-news.html, test/spec/unit/modules/youtubeTest.js
Non-youtube video embeds in articles are broken on iOS and Android. 
This is because they need to be wrapped in an `<a>` tag. All `<a>` in the body currently have a style applied to them from the `text-underline` mixin, this applies a nice underline effect on links, but it shouldn't be used on `video-url` links, so I've put a `not(.video-url)`  exception on this mixin, which fixes the issue.
Before...
After...
=> Fix issues with embed video links

ArticleTemplates/assets/scss/garnett-helpers/_mixins.scss
`yarn develop` began falling over once this PR was merged https://github.com/guardian/mobile-apps-article-templates/pull/795 because of a clash between the `:not(.video-URL)` and the nested `&:hover`, 
I've pulled the pseudo selectors `a:not(.video-URL) a:active`, `a:not(.video-URL):hover` out into their own block.
=> fix dev server bug caused by invalid scss

ArticleTemplates/assets/scss/garnett-modules/_advert-slot.scss
The text-underline mixin was adding pillar-coloured underlines to the adverts' "Hide" button, and this removes them.
**After**
CC @jorgeazevedo
=> Remove underline from advert 'hide' button

ArticleTemplates/articleTemplate.html, ArticleTemplates/articleTemplateContainer.html, ArticleTemplates/articleTemplateContainerComment.html, ArticleTemplates/articleTemplateContainerFeatures.html, ArticleTemplates/articleTemplateContainerImmersive.html, ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/scss/modules/_resizable.scss, ArticleTemplates/audioTemplate.html, ArticleTemplates/collectionTemplate.html, ArticleTemplates/commentsTemplate.html, ArticleTemplates/commentsTemplateBlock.html, ArticleTemplates/cricketTemplate.html, ArticleTemplates/errorExpiredContent.html, ArticleTemplates/footballTemplate.html, ArticleTemplates/galleryTemplate.html, ArticleTemplates/interactiveTemplate.html, ArticleTemplates/liveblogTemplate.html, ArticleTemplates/liveblogTemplateBlock.html, ArticleTemplates/videoTemplate.html, yarn.lock
This work is related to this ticket in the Android board:
https://theguardian.atlassian.net/browse/AA-73
This adds the ability to call `lineHeightResize()` from native iOS or Android code which allows the line spacing for the body text in articles to be changes at runtime. 
This is my first foray into the templates in any substantial way so let me know if there's any gotchas that I might have fallen in to, however from my testing everything seems to be working correctly.
Screenshots: https://photos.app.goo.gl/AHv7PfYZNqZp5dez8
1. Shows the new dialog with the slider
2. Shows the default line spacing (the same as previously)
3. Shows the maximum line spacing
=> AA-73 - Implement Line Height in Templates

ArticleTemplates/assets/js/modules/cards.js
The related content wasn't being positioned correctly on some articles - Live blogs and articles containing Tweets for example. Adding `childList` to the list of items to observe seems to solve this problem. There may be performance issues with this though I haven't observed any.
=> Add childList mutations to the list of items to observe because it seems to be necessary

ArticleTemplates/assets/js/bootstrap.js, ArticleTemplates/assets/js/bootstraps/liveblog.js
This PR adds a function that will be called by the native layer passing the id of a Live Blog block in order to scroll that block into view. The [SmoothScroll](https://github.com/cferdinandi/smooth-scroll) library needed to be used here because [Safari on iOS doesn't yet support smooth scrolling](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) when using `window.scrollIntoView()`
=> Define and expose function for allowing Live Blog block to be scrolled to smoothly.

ArticleTemplates/assets/js/modules/cards.js
there's a call `window.webkit.messageHandlers.bodyMutationNotification` in `cards.js`,`window.webkit.messageHandlers.bodyMutationNotification` is defined by the native iOS app so works fine on an iOS device (this line of code will never run on Android).
Unfortunately if you're developing in your local browser using a fixture pulled from the iOS app this line of code will execute and throw an error as it's undefined. This PR prevents that by wrapping the call in a conditional that checks for it's existence.
=> Check for message handlers

ArticleTemplates/assets/js/bootstraps/liveblog.js
To allow us to tracking how often users are attempting to link to blocks that are not within the first 10.
=> Return a value so that we can track the success of the scroll

ArticleTemplates/assets/js/bootstraps/campaign.js, ArticleTemplates/assets/scss/modules/_campaign.scss
- there was no styling by default when not in a pillar: it shouldn't happen, it does on the test mobile because they use a weird pillar called "test" or something like that 😅 
- added CORS headers in API gateway
- fixed the wiring of checkbox values
=> Fix button styling when not in pillar and data wiring

ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/js/bootstraps/campaign.js
The components at the bottom of articles belong in the native layer. As a result, when the geometry of the article changes, a process must update the position of these components so that they don't overlay the content (or a huge whitespace appears). There is a polling process in place that regularly checks and updates the geometry if necessary, but it has a back-off polling time. As a result, when opening a callout (for instance), there is a lag between the moment the article height changes and the components at the bottom are repositioned: this creates an ugly/broken visual effect, especially if the callout is at the bottom of the article.
This solution remedies the problem by explicitly requiring a geometry update every time an expandable atom/callout is either opened or closed.
=> Update article geometry with callouts and snippets

ArticleTemplates/assets/js/bootstraps/campaign.js
Reverts guardian/mobile-apps-article-templates#811
Testing from @SLambrakis and the Android team suggests that this change has stopped submit working on the forms. 
If we want to use `req.withCredentials = true;` we need to set the `Access-Control-Allow-Origin` header to point to the app url. 
```
req.setRequestHeader('Access-Control-Allow-Origin', 'https://guardian.co.uk');
req.setRequestHeader('Vary', 'Origin');
```
We should return to the use of `withCredentials` before rolling this out to editorial
=> Revert "Enable CORS"

ArticleTemplates/simpleBodyTemplatePrepopCancelAppleSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelDigipackSubscription.html, ArticleTemplates/simpleBodyTemplatePrepopCancelSubscriptionAndroid.html, ArticleTemplates/simpleBodyTemplatePrepopCredits.html
Apps were no longer populating style sheet placeholders.
----------
----------
=> hardcode style sheets

ArticleTemplates/assets/js/bootstraps/campaign.js, ArticleTemplates/assets/scss/modules/_campaign.scss
Reader callout forms should show a "Waiting" message if the form is waiting to be submitted 
On poor connections this can be up to 12 seconds. 
Connected PR: https://github.com/guardian/mobile-apps-api/pull/1203
=> Callout campaigns: Add waiting message to callout form

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
Reverts guardian/mobile-apps-article-templates#820
Found a case that displays two captions: https://www.theguardian.com/cities/2018/aug/13/halfway-boiling-city-50c
=> Revert "stop hiding captions"

ArticleTemplates/assets/scss/modules/blocks/_comment.scss
Missed a case where links were hard to read in the preview:
After:
=> make links readable in preview

ArticleTemplates/assets/scss/garnett-modules/cricket/_match-summary.scss
iPad pro landscape screen width not currently handled:
=> increase width for large tablet screens

ArticleTemplates/assets/scss/layout/_article--sponsorship.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/style-sync.scss, ArticleTemplates/assets/scss/type/_guardianlabs.scss
| Before | After
|---|---|
| ![screen shot 2018-09-03 at 14 37 15](https://user-images.githubusercontent.com/11618797/45000470-0c02f400-afbd-11e8-8446-03044ce7cabb.png) | <img width="434" alt="screen shot 2018-09-03 at 21 03 06" src="https://user-images.githubusercontent.com/11618797/45000473-10c7a800-afbd-11e8-8601-f932df1e3855.png"> |
| ![screen shot 2018-09-03 at 14 35 08](https://user-images.githubusercontent.com/11618797/45000475-145b2f00-afbd-11e8-9352-5619d25902c7.png) | <img width="394" alt="screen shot 2018-09-03 at 21 03 50" src="https://user-images.githubusercontent.com/11618797/45000476-17561f80-afbd-11e8-95d5-f784f1b6cfc8.png"> |
| ![screen shot 2018-09-03 at 11 01 29](https://user-images.githubusercontent.com/11618797/45000479-1ae9a680-afbd-11e8-8411-0ce951f35acf.png) | <img …
=> GuardianLabs style improvements

ArticleTemplates/assets/scss/base/_typography.scss
This PR works in conjunction with this PR against the [Android repo](https://github.com/guardian/android-news-app/pull/4714) to replace the old EgyptianText fonts with the new GuardianTextEgyptian ones.
The Android app will provide these fonts from its codebase for now, rather than importing them from templates repo, so that iOS don't have to include unused fonts in their app bundle. But I have prepared a second PR for the templates repo (#843) to resolve this, which we can merge later when iOS are happy with the change.
This and first templates PR above combined fix the issue raised by Kath's brother that Zach emailed us about. You can see some screenshots on [the Android PR](https://github.com/guardian/android-news-app/pull/4714).
=> Use GuardianTextEgyptian on Android (AA-561)

ArticleTemplates/assets/scss/type/_immersive.scss, ArticleTemplates/interactiveTemplate.html
- Only styles sent to ``` immersive interactives``` is interactives.css
- Removed ```async-styles``` being included
=> Reduce css on interactives page

ArticleTemplates/assets/js/modules/rich-links.js
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48765167-859bab80-eca9-11e8-96e2-ecc44fb662af.png" width="300px"/> | <img src="https://user-images.githubusercontent.com/11618797/48765197-91876d80-eca9-11e8-8c16-f3b4158b1988.png" width="300px"/> |
=> Correctly display rich links above tweets and embeds

ArticleTemplates/assets/scss/base/_reset.scss, ArticleTemplates/assets/scss/layout/_article--audio.scss, ArticleTemplates/assets/scss/layout/_article--liveblog.scss, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/layout/_base-tone.scss, ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/modules/_container.scss, ArticleTemplates/assets/scss/modules/_related-content.scss, ArticleTemplates/assets/scss/modules/_tags.scss, ArticleTemplates/assets/scss/outbrain.scss
- Update background of related content + outbrain to match native iOS colour
- Update related content + outbrain borders to match fronts
- Use the same font and size for both titles
- Remove more hover states in outbrain container
- Fix alignment of guardian labs outbrain on iPad pro
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11618797/48707266-c4245e00-ebf6-11e8-8a41-241c1fc74e42.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/48707280-d1d9e380-ebf6-11e8-80b0-886f35ac46fc.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/11618797/48707302-eb7b2b00-ebf6-11e8-8c72-94bebae56e8d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/11618797/48707313-f7ff8380-ebf6-1 …
=> Related content and outbrain cleanup

test/spec/unit/bootstraps/audioTest.js
@webb04 woops, forgot to run the tests.
The function now depends on finding the `audio-player-readable` span to work.
=> Fix audioPlay() test

ArticleTemplates/assets/js/bootstraps/audio.js, ArticleTemplates/assets/scss/modules/media/_audio-player.scss, ArticleTemplates/audioTemplate.html, test/fixtures/audio-news-loading.html, test/fixtures/audio-news.html
Using the existing loading state to show content is loading (this can be quite long, especially on slow 3g/4g connections).
The logic to add a loading state is there so we can update the design to anything else.
Could also animate the play/pause icons to make it less jumpy.
| Current | Suggested |
| --- | --- |
| ![current](https://user-images.githubusercontent.com/11618797/48941892-3ce82a80-ef15-11e8-8480-0eba8f292e6c.gif) | ![after](https://user-images.githubusercontent.com/11618797/48941917-52f5eb00-ef15-11e8-8a99-1c8357146954.gif) |
=> Add loading state once audio requested

ArticleTemplates/assets/js/modules/creativeInjector.js
Currently set up on CODE as ``` in-article-signup-test ```. This will need migrating to PROD Olgil and the parameters set up.
https://olgil-admin.code.dev-gutools.co.uk/admin/creatives
=> New inline creative type

ArticleTemplates/interactiveTemplate.html
Some interactive templates (docs) still use the require keyword and rely on it being in window scope.
=> alias curl to require

ArticleTemplates/articleTemplate.html, ArticleTemplates/collectionTemplate.html, ArticleTemplates/commentsTemplate.html, ArticleTemplates/commentsTemplateHighlighted.html, ArticleTemplates/cricketTemplate.html, ArticleTemplates/errorExpiredContent.html, ArticleTemplates/footballTemplate.html, ArticleTemplates/galleryTemplate.html, ArticleTemplates/liveblogTemplate.html
Some interactive templates still rely on having the require variable in the window scope.
We should alias it to curl just in case.
=> Alias require to curl on pages that could rely on having require

ArticleTemplates/assets/scss/modules/media/_gallery.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/53240224-08ac1380-3696-11e9-9938-bf12ee702678.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/53240223-08ac1380-3696-11e9-9c94-c3c5269f1ec8.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/53240316-5163cc80-3696-11e9-81c5-5c40f2daf30c.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/53240329-5aed3480-3696-11e9-985b-ad838dbe66c8.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/53240483-b7e8ea80-3696-11e9-9ba3-faf3252fc5fc.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/53240494-bcad9e80-3696-11e9-836a-5e3eeca825ce.png" …
=> Show top of gallery images

ArticleTemplates/assets/js/bootstraps/atoms.js
This is a temporary hack required for launching chart atoms in the UI. They currently are added in the form of an iframe with local source:
```html
<iframe srcdoc="@atomHtml"></iframe>
```
and inside that code is some JavaScript that is sending messages to the parent document. This must be controlled in such a way that we have a listener able to handle those messages before they are sent. Hence the local complexity.
=> Add bootstrap for charts

ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/scss/base/_reset.scss
There was some issue bootstrapping charts because of the weird need for iframes, so I factored them out of the normal atom bootstrap. Then this fix highlighted issues with how iframes are rendered in the app.
| --- | --- |
|![53641456-e894cb00-3c26-11e9-8cf3-00b19473f934](https://user-images.githubusercontent.com/629976/54121379-2e554e80-43f2-11e9-838e-9e1342fde53e.png)|![Screen Shot 2019-03-11 at 11 37 11](https://user-images.githubusercontent.com/629976/54121319-11208000-43f2-11e9-975f-901a5a537eef.png)|
=> Charts and iframes fixes

ArticleTemplates/assets/scss/base/_inverted.scss, ArticleTemplates/assets/scss/layout/_article--shared.scss, ArticleTemplates/assets/scss/modules/_cutout.scss, ArticleTemplates/assets/scss/modules/_tags.scss, ArticleTemplates/assets/scss/style-async.scss, ArticleTemplates/assets/scss/style-sync.scss
This is a fix to smart inversion on:
- article cutout images (https://www.theguardian.com/education/2019/mar/19/uk-government-runs-down-schools-laura-mcinerney)
- tags (any article with tags!)
- YouTube videos embedded within article body (https://www.theguardian.com/tv-and-radio/shortcuts/2019/mar/19/crushed-giant-cheese-10-greatest-celebrities-moments-midsomer-murders)
- interactives within article body (https://www.theguardian.com/culture/ng-interactive/2019/mar/17/simone-lia-banana-split)
Taking screenshots with Smart Invert on doesn't really work, so I've provided links to the relevant sections in case you want to see the changes yourself.
=> GLA-1101: fix smart inversion

ArticleTemplates/galleryTemplateImages.html
It launches the native slide view for all display images (not currently the header image). But this is duplicated in the displayImage.
=> Gallery swipe view

ArticleTemplates/assets/scss/modules/_comments.scss, ArticleTemplates/assets/scss/modules/_commentsHighlighted.scss, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/_tags.scss, ArticleTemplates/assets/scss/type/_live.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/61218834-db2a3a00-a70a-11e9-95f4-bd9af8068923.PNG" width="300px" />| <img src="https://user-images.githubusercontent.com/11618797/61218833-da91a380-a70a-11e9-87b2-ac8bab4ccae4.PNG" width="300px" />|
=> match ios styles

ArticleTemplates/simpleBodyTemplatePrepopCredits.html
I've added license information for ESTabBarController, which will be added in https://github.com/guardian/ios-live/pull/4447.
=> Add ESTabBarController acknowledgement

ArticleTemplates/assets/js/modules/ads.js
On short articles (<9 paragraphs), there is only space for one ad slot. While this was being correctly added, `adsReady` was not being set to true, which meant that the native code never filled the slot.
This change breaks out of the loop but not the function, ensuring that `adsReady` will always be set. I have tested this locally, and can see that the slot is now correctly filled.
You can test this on any short article - I have a Charles response saved if you can't find one.
=> Call ads-ready on short articles with only one ad

ArticleTemplates/assets/js/liveblog.js
It's been reported a few times that atoms embedded in liveblogs work on web but not on apps. This will address the issue, at the same time for campaign callouts as well.
=> Kick-off atoms and callouts in liveblogs

ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/js/modules/util.js, ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/modules/_related-content.scss, ArticleTemplates/assets/scss/style-async.scss, ArticleTemplates/assets/scss/type/_media-gallery.scss
1. Reinstated the ad slot, and fixed the margin
2. Made the related content container the same colour as the article body to make it more consistent
3. Add some color and underline to links (using this article as a guideline (App version not dotcom): https://www.theguardian.com/rdg-epic-rail-journeys/2019/aug/01/views-box-set-binges-and-reducing-co2-nine-reasons-to-love-train-travel) 
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/62882089-0d8a7f80-bd29-11e9-9dc5-07138922c3cc.PNG" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/62882131-23984000-bd29-11e9-8d11-540d785985c6.png" width="300px" />|
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/62882276-7671f780-bd29-1 …
=> MSS-1064: gallery lab fixes

ArticleTemplates/assets/js/bootstraps/liveblog.js
The newly-introduced (and not yet used on iOS) function `scrollToBlock` accepts a block id, but it's requiring the native layer to remove the `block-` prefix from the id... because the function itself prepends it to the supplied id!
That is, as far as I know, the only place where we're doing such a thing, hence this PR :)
[Agreed with @jordanterry that we can change the behaviour of the Android app to match]
=> liveblog.js: let native layers pass block id as-is

ArticleTemplates/articleTemplateBadge.html, ArticleTemplates/articleTemplateContainer.html, ArticleTemplates/articleTemplateContainerComment.html, ArticleTemplates/articleTemplateContainerFeatures.html, ArticleTemplates/assets/scss/modules/content/_article-kicker.scss, ArticleTemplates/liveblogTemplate.html, ArticleTemplates/videoTemplate.html
We'd like to show badges in the kicker on articles related to the upcoming general election. This provides new placeholders and styling/layout changes needed by the apps, so they can inject the new badge information. Immersives coming in later PR.
- Corresponding PR on Android [here](https://github.com/guardian/android-news-app/pull/5689).
- Corresponding branch on iOS [here](https://github.com/guardian/ios-live/compare/temporary-ge2019-badge).
cc @benwuersching 
- New `articleTemplateBadge` template with `__BADGE_URL__` and `__BADGE_NAME__` placeholders.
- Tweaked the templates for standard articles, opinion, features, liveblogs and video to accommodate the new badge.
- CSS changes to re-style the kicker; I've scoped these as much as possible to pages that include the badge, so hopefully …
=> Temporary GE2019 Badge

ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/type/_immersive.scss, ArticleTemplates/seriesTemplateImmersive.html
Follow-up to #1110 as promised. This adds the election badge to immersive articles.
FYI @benwuersching 
- Added the badge and name to the series template for immersives.
- Applied styles to accomodate the badge and new line of text.
|| Non-Election | Election |
|-|-|-|
iPhone 11 | ![normal](https://user-images.githubusercontent.com/53781962/69723662-0ccbfc80-1112-11ea-983d-0be82e15d265.jpeg) | ![badge](https://user-images.githubusercontent.com/53781962/69723661-0ccbfc80-1112-11ea-8183-90ec5e6fe9d5.jpeg)
iPad Pro 11" | ![ipad-normal](https://user-images.githubusercontent.com/53781962/69724313-90d2b400-1113-11ea-887f-fd29e581f284.jpeg) | ![ipad-badge](https://user-images.githubusercontent.com/53781962/69724314-90d2b400-1113-11ea-94dc-3098ea49565b.jpeg)
=> Immersive Election Badges

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/69859866-f0a09a80-128c-11ea-91bd-68955be24cda.jpg" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/69859870-f302f480-128c-11ea-884c-673278263fe0.png" width="300px" />|
=> white background for embeds in dark mode

ArticleTemplates/assets/js/bootstraps/liveblog.js
With the new key event link feature, blocks can be loaded in at any point of the liveBlog. This means they may not be in the most recent 10.
=> format all images

package-lock.json, package.json
There was [a vulnerability](https://github.com/advisories/GHSA-h9rv-jmmf-4pgx) reported in `serialize-javascript`, which appears in this project as a transitive dependency of webpack (via `terser-webpack-plugin`), `terser-webpack-plugin` and `copy-webpack-plugin`. This was fixed in patch releases for [v1](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v1.4.2) and [v2](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v2.2.2) of the terser plugin. I think the `copy-webpack-plugin` should pick up the patched release of `serialize-javascript` as of [v5.0.5](https://github.com/webpack-contrib/copy-webpack-plugin/compare/v5.0.4...v5.0.5).
**Note** I've updated across a major release (v1 -> v2) for our direct dependency on `terser-webpack-plugin`. This …
=> Update webpack, and the terser and copy plugins

ArticleTemplates/assets/scss/modules/content/_article-kicker.scss
Changes badges to have a fixed height instead of width, as requested by @benwuersching 
| Election | Europe |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/75555324-ec268200-5a33-11ea-99c8-35fb17672abd.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/75555359-f9dc0780-5a33-11ea-8bfb-806bbe4a92a6.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/19835654/75557946-e8492e80-5a38-11ea-94d6-f8b68aa5d2b8.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/75557994-fac36800-5a38-11ea-875a-6ca14b66a63d.png" width="300px" />|
=> Change badge from fixed width to fixed height

ArticleTemplates/assets/scss/themes/darkMode/_darkModeSpecialReport.scss, ArticleTemplates/assets/scss/tones/_tone--special.scss
Fixes some visual bugs that occur for the series highlight on special reports.
Removing the padding fixes the vertical yellow line on articles with no series. Altering the box shadow makes the highlight smaller (partially solving the overlap bug), and takes on the work that the padding was doing. Tweaking the line height also helps with the overlap.
- Removed padding, used box-shadow instead
- Tweaked line height to prevent overlap with section
- Applied to dark mode as well
|| Before | After |
| - | --- | --- |
| Series Highlight | ![before](https://user-images.githubusercontent.com/53781962/75684812-6e5fb200-5c91-11ea-9487-803b903a1619.jpg) | ![after](https://user-images.githubusercontent.com/53781962/75684811-6dc71b80-5c91-11ea-8cb7-6ed60a463a4a.jpg)
| iPad Series Highlight | …
=> Fix Special Report Series Highlight Bugs

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
@rupertbates reported low contrast on interactive atoms in dark mode. This should fix that, although I'm not sure if there's likely to be a knock-on effect of this change elsewhere.
- Removed white colour from heading
- Applied dark colour to links
| --- | --- |
| ![dark-before](https://user-images.githubusercontent.com/53781962/75875953-a5a69e00-5e0c-11ea-9278-f74250d81ab2.png) | ![dark-fix](https://user-images.githubusercontent.com/53781962/75875950-a2abad80-5e0c-11ea-89fc-8af25be354ad.png) |
=> Fix Contrast On Atoms

package-lock.json, package.json
Patches some issues reported by `npm audit`, applies patches marked as non-breaking (i.e. non-major semver version updates).
- Ran `npm audit fix` to bump `node-sass` and other libraries
=> Non-Breaking Patches

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss, package-lock.json
Quotes need to be in light gray. Can you please validate @benwuersching ?
https://theguardian.atlassian.net/browse/GLA-1877
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 - 2020-03-13 at 17 30 13](https://user-images.githubusercontent.com/1733570/76645269-8fa58580-6550-11ea-9fdb-921be2c1987c.png) | ![Simulator Screen Shot - iPhone 11 - 2020-03-13 at 17 27 50](https://user-images.githubusercontent.com/1733570/76645272-916f4900-6550-11ea-8ecf-63139fe7b5fc.png) |
=> GLA-1877: update quotes color to normal body color

ArticleTemplates/assets/scss/modules/_resizable.scss, ArticleTemplates/assets/scss/modules/galleryImageViewCaption.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeArticle.scss, ArticleTemplates/assets/scss/type/_media-gallery.scss
- Increased line-height for text on gallery pages
- Use grey with underline for media links (dark mode)
- Remove underline in rich links (dark mode)
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/76762747-c61a1500-6789-11ea-85b3-0adce297dace.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/76762765-cdd9b980-6789-11ea-8f18-626e02209c5f.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/76762784-daf6a880-6789-11ea-9f3c-9d84ca2d13e8.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/76762809-e3e77a00-6789-11ea-946c-78b8375682eb.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/76762823-eb0e8800-6789-11ea-9e3b-d64 …
=> media dark mode links

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/layout/_article.scss, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/liveblogTemplate.html, test/spec/unit/modules/ads.test.js
This pr sends an array of ad slot positions instead of comma separated string values for iOS and individual integers to Android.
Before we were showing two ads per article after the 3rd and 9th paragraphs, now we will show ads after the 3rd, 9th and after every following 6 paragraphs.
- This extends our existing logic but we can tweak it
- I've set a remote limit of 15 but this can be extended too
- `__MAXIMUM_ARTICLE_ADVERTS__` is the remote config value that needs passing from iOS and Android (I've raised a PR in mobile-static)
I've not changed the names yet, but I think the function iOS calls `getMpuPosCommaSeparated` should be renamed to something like `getAdSlots`. We might also need to change to postMessage to be able to send arrays and objects from the webview to iOS: …
=> variable ad slots

ArticleTemplates/assets/scss/modules/_advert-slot.scss
Use dark mode ad slot styles for light mode gallery pages. 
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/77643612-9de3a080-6f57-11ea-8eee-28164fbf4d1f.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77643642-a8059f00-6f57-11ea-8503-146f6518ced6.png" width="300px" />|
=> use darker slot for gallery adverts

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/liveblogTemplate.html, test/spec/unit/modules/ads.test.js
- Move adverts further to the right to avoid clashes with body content.
- Remove remote configuration as this needs to be added in iOS and Android
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/77658238-4f8dcc00-6f6e-11ea-85c3-08d72b11db3c.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77658280-603e4200-6f6e-11ea-82f6-7d0a3f117eb9.png" width="300px" />|
=> move ad slots further to the right

ArticleTemplates/assets/scss/themes/darkMode/_darkModeSpecialReport.scss
I hate using `!important`. It's one of the most annoying feature of CSS. But I'm not sure I have too much choice here, because I use it only to override others, existing `!important`, located in `_darkModeArticle.scss`. (That's precisely what makes `!important` annoying: once we start using it, it proliferates.)
I don't want to touch/change *these*, in turn, because I suspect this would break other stuff in other places (otherwise they wouldn't be here in the first place), and I don't think it'd be worth to refactor the whole article CSSes just to get Special Report colours done.
So, here you go. These fixes are based on designs available from: https://theguardian.atlassian.net/browse/GLA-1880
You can repro locally by using CODE MAPI and opening the World/Europe front (PROD MAPI would …
=> GLA-1880: fix Special Report article colours in dark mode

ArticleTemplates/assets/scss/modules/_advert-slot.scss
A recent change to ad slots caused this issue on gallery pages.
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/77923609-934c4280-729a-11ea-90b6-de9342dc39cc.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/77923657-a6f7a900-729a-11ea-869d-ab5f04a5b18d.png" width="300px" />|
=> center gallery adverts on tablets

package-lock.json, package.json
To deal with issues in transitive dependencies, and to keep our top-level deps up-to-date.
- Bumped `@babel/preset-env` to latest
=> Bumped @babel/preset-env To Latest

.snyk, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/modules/_figure.scss, ArticleTemplates/assets/scss/modules/content/_prose.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeImmersive.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
- Stop adverts overlapping on large tablets
- Remove margin for thumbnail images on large tabelts
- Darker blockquote borders (dark mode)
- More email sign up styles (dark mode)
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/78669263-eabe6400-78d3-11ea-89da-ce73af1aae85.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/78669286-f3169f00-78d3-11ea-998c-c8e910151154.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/78669308-fb6eda00-78d3-11ea-8762-c533fd231c01.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/78669335-0590d880-78d4-11ea-9c34-d1d9efbb22f8.png" width="300px" />|
|<img src="https://user-images.githubusercontent.com/11618797/7866936 …
=> clear adverts

ArticleTemplates/assets/scss/layout/_article--photo-essay.scss
Dotcom use these styles, authors will assume they'll also be on apps.
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/79765070-10a92700-831e-11ea-8d98-2e6da60618d6.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/79765146-2880ab00-831e-11ea-9184-f420549de960.png" width="300px" />|
=> clear pullquotes on photo essays

package-lock.json, package.json
Keeps webpack up to date.
## Changes
- Bump webpack to 4.43.0
=> Bump Webpack To 4.43.0

ArticleTemplates/assets/scss/modules/_injectedCreative.scss
Fix for the epic using the pre-garnett _Guardian Egyptian_ instead of _Guardian Headline_ for headlines, and _Guardian Headline_ instead of _Guardian Text Egyptian_ for body text.
<h3>Before</h3>
<h3>After</h3>
=> Use the correct fonts in injected creatives

package-lock.json, package.json
Keeps `node-sass` up-to-date. Should fix an issue with the incorrect `libsass` version being reported (release notes [here](https://github.com/sass/node-sass/releases/tag/v4.14.0)).
- Bumped `node-sass` to `4.14.0`
=> Upgrade node-sass to 4.14.0

ArticleTemplates/assets/scss/modules/_injectedCreative.scss
I realised my PR from yesterday removed a right margin on the button that is necessary — when two buttons are side-by-side, rather than vertically stacked!
=> Space two buttons side-by-side in injected creatives

ArticleTemplates/assets/scss/base/_typography.scss
Warning • This is confusing:
The app currently loads a font, 'Guardian Egyptian Web', which is no longer in use — and can be replaced by 'Guardian Headline' in all instances.
Unfortunately, dotcom loads 'Guardian Headline' under the 'Guardian Egyptian Web' name (i.e the wrong name, which is likely done for backwards compatibility). This leads to things on the app using the wrong font occasionally — mostly in things that are originally implemented for the web. We can fix them individually (like #1160) but we'd always be playing catch-up.
This PR makes 'Guardian Egyptian Web' an alias for 'Guardian Headline' for compatibility with dotcom. It doesn't delete the font files, in case they're needed by the native layer (another PR will follow for that).
=> Compatibility with dotcom on 'Guardian Egyptian Web' font name

ArticleTemplates/assets/scss/themes/darkMode/_darkModeQuiz.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/81161138-fe1c2800-8f82-11ea-831d-1285ff4fd820.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/81161159-08d6bd00-8f83-11ea-8d50-2f48b9494425.png" width="300px" />|
=> use white text for quiz message in dark mode

package-lock.json, package.json
Keeps `node-sass` up to date, and *should* fix reported issue with `yargs-parser`.
- Bumped `node-sass` to 4.14.1
=> Bumped node-sass To 4.14.1

ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/assets/scss/modules/_live-promo.scss, ArticleTemplates/liveblogTemplateLivePromo.html
When the button is pressed, we remove the card from the DOM. We also need to send a signal to the app so that we register the closure and we don't reopen the card. You can test this PR by following the steps on https://github.com/guardian/ios-live/pull/5203
| --- | --- |
|<img src="https://user-images.githubusercontent.com/1733570/84163829-d16b9c80-aa69-11ea-8f41-a2cfdc85f675.png" width="300px" />|<img src="https://user-images.githubusercontent.com/1733570/84163849-d597ba00-aa69-11ea-910d-c286c14135a2.png" width="300px" />|
=> GLA-2087: Try Live: add close button

ArticleTemplates/assets/js/bootstraps/liveblog.js
I forgot to add logic to dismiss the card when pressing the "Try Live" button itself. We do want to do this because once people went ahead and tried it we don't need to advertise it anymore, and it wouldn't show on subsequent LiveBlog renders. @jordanterry does it make sense for Android's logic as well?
=> GLA-2087: dismiss Try Live when pressed

ArticleTemplates/assets/scss/modules/content/_standfirst.scss
This reapplies #1165 but now plays well with liveblogs and comment articles.
Comment — keylines still full-width
Liveblog — the narrow standfirst no longer applies to these:
(Edit fixed a :not, :not logic mistake)
=> Narrower standfirsts

package-lock.json, package.json, webpack.config.js
Keeping dependencies up-to-date.
- Updated call to plugin constructor to use object with `patterns` field
=> Bump copy-webpack-plugin To 6.0.3

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/89394444-fdbb3680-d703-11ea-814a-737d3308ef72.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/89394474-06ac0800-d704-11ea-9b4a-63ff8362ea93.png" width="300px" />|
=> use light background in dark mode for chart atoms

.gitignore, ArticleTemplates/assets/js/bootstraps/common.js, ArticleTemplates/assets/js/modules/ophan-iframe.js
This work is part of a larger piece to ensure the newsletter team closes the data gap we have as much as possible.
Part of that work is understanding when people are signing up to newsletters, which are currently implemented using iFrame embeds. Some work [has been done](https://github.com/guardian/frontend/pull/22806/files) on dotcom such that a message is posted from within the iFrame to the outer frame.
This PR implements a handler to receive the message, and forward it to the native layer. Unfortunately, the iOS stack blocks the message because of the security policy of the webview, so we'll only have Android support until the apps-rendering project reaches maturity.
See [this PR](https://github.com/guardian/android-news-app/pull/6241) for the android work that forwards the message to …
=> Support iframe click tracking

package-lock.json
Keeping dependencies up-to-date. `npm i` also tweaked a couple of other deps, which is unusual.
- Bumped `lodash` to 4.17.20
- `npm i` also tweaked a couple of existing deps
=> Lodash 4.17.20 And Dep Tweaks

package-lock.json
Keeping dependencies up-to-date.
- Bumped `ajv` to 6.12.4
=> Ajv 6.12.4

package-lock.json, package.json, webpack.config.js
Manually bumping this to fix a failing build. 
The only difference is removing the `minimize` option as it was deprecated in v2 so no longer needed.
See original dependency bot PR: https://github.com/guardian/mobile-apps-article-templates/pull/1231
=> Update css-loader to 4.3.0

ArticleTemplates/assets/scss/layout/_support.scss
I think this might have been the first image used on one of our support articles...
| --- | --- |
|<img src="https://user-images.githubusercontent.com/11618797/95738018-7c8e9b80-0c80-11eb-9bae-915fe83ed64a.png" width="300px" />|<img src="https://user-images.githubusercontent.com/11618797/95738035-844e4000-0c80-11eb-8678-ca54829d81f2.png" width="300px" />|
=> set image sizes on support articles

ArticleTemplates/articleTemplate.html, ArticleTemplates/assets/js/bootstraps/article.js, ArticleTemplates/assets/js/modules/premiumTaster.js, ArticleTemplates/assets/scss/base/_colour.scss, ArticleTemplates/assets/scss/modules/_premium-taster.scss, ArticleTemplates/assets/scss/style-sync.scss
---
Requires iOS branch: LIVE-616-iOS-taster-ad-slot
Inserts graphic into article in place of the first advert. When scrolled into view, the action is reported to iOS so that we don't show it for following articles.
Only supported on iPhone at the moment.
---
- Do we need an Android equivalent to the iOS branch? @maxspencer @jordanterry 
---
=> Premium taster ad slot

ArticleTemplates/assets/js/modules/premiumTaster.js
Paired with @GiuliaAriu on this
The web premium taster indicators' accessibility was broken. This PR fixes it.
=> Fix a11y for premium taster indicators

ArticleTemplates/assets/scss/modules/_premium-taster.scss
Native browser css on Android draws a 3D border around the dismiss button in premium taster card. This update explicitly sets border-width to zero to remove any border, in line with the designs.
| | Before | After |
| --- | --- | --- |
| No Ads |<img src="https://user-images.githubusercontent.com/2292388/100249207-36da1980-2f34-11eb-82fb-a14c9841b9c2.png" width="300px" />|<img src="https://user-images.githubusercontent.com/2292388/100249217-3a6da080-2f34-11eb-9458-1601b4a823bb.png" width="300px" />|
| Offline |<img src="https://user-images.githubusercontent.com/2292388/100249215-393c7380-2f34-11eb-9d6d-2923425538b7.png" width="300px" />|<img src="https://user-images.githubusercontent.com/2292388/100249221-3b063700-2f34-11eb-8e1b-3c815721be33.png" width="300px" />|
=> Remove border for dismiss button in premium taster explainers

package-lock.json
Keeps dependencies up to date.
- Bumped y18n to 4.0.1
=> Bump y18n To 4.0.1

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
I moved to dark-mode sponsor logos on fronts in an earlier pr in `android-news-app`. However, the grey background in articles prevented me from making the same change in articles.
This PR removes the grey background so that articles can also be switched to the dark-mode `altLogo` in `android-news-app`.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/34686302/112474028-ff0aa380-8d66-11eb-9bfb-386e8b12bf93.png) | ![image](https://user-images.githubusercontent.com/34686302/112474047-05008480-8d67-11eb-998f-de61b233a5af.png) |
=> Removed grey background-color from dark mode sponsorship logos

package-lock.json
=> Bump Lodash To 4.17.21

ArticleTemplates/assets/js/modules/quiz.js, ArticleTemplates/assets/js/modules/util.js, ArticleTemplates/simpleBodyTemplatePrepopHelpAndroid.html, package.json, webpack.config.js
Users have written to us about the smooth scrolling animation we use (particularly for skipping to certain live blog blocks) being unsuitable.
Priscilla has confirmed we ought to remove this effect. This came through as an Android ticket, but I found it was actually a templates thing and thought I could probably fix it myself. I did a quick Google search and came up with using the built-in [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) function.
This PR comprises two commits:
1. removes the smooth scroll animation from live blogs as the ticket requires
2. removes one other remaining use of the `smooth-scroll` dependency and that dependency itself.
Please check I've done (2) correctly, but I have built and run this branch locally and it all …
=> [LIVE-2137] Remove smooth scrolling animations

package-lock.json
- Bumped `hosted-git-info` to 2.8.9
=> Bump `hosted-git-info` To 2.8.9

package-lock.json
It's no longer a dependency as of #1360.
- Remove `smooth-scroll` from `package-lock.json`
=> Remove `smooth-scroll` From `package-lock.json`

package-lock.json, package.json
`ssri` is a transitive dependency of a few things. As a result, I've reinstalled `copy-webpack-plugin` and `terser-webpack-plugin`. Technically their resolved versions haven't changed (they were already on 6.4.1 and 4.2.3 respectively in the lockfile), but some of their other transitive deps have been bumped.
- Bumped `ssri` to 8.0.1 and 6.0.2
=> Bump `ssri` To 8.0.1 And 6.0.2

package-lock.json
- Bumped `node-notifier` to 8.0.2
=> Bump `node-notifier` To 8.0.2

ArticleTemplates/assets/scss/modules/_cutout.scss
Contributors Link not working specifically when a cut_out image is present on the comment article.
The `cutout_image` layer is in front of the `headline` tag and therefore not allowing us to click on the contributor anchor.
The cut out `<div>` is covering the whole top area.
- Finally decided to use `pointer-events:none`
- Adding css property pointer-events: none; to the #other-div will let clicks or other pointer-related events to pass through the div and reach both the canvas and the container
**_For Reference_**
1. Initial investigation:
| Cut_Image Layer with bg-color | Headline layer  and cut_out image with z-index of 100 |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/49187886/117962003-a727fc00-b316-11eb-913f-b881bddfbc3e.png" width="300px" />|<img …
=> Live: 2399 - Dead contributor links not working with `cut_out image`-present

ArticleTemplates/assets/scss/modules/_advert-slot.scss
We want to serve square ads on narrower devices, and rectangular ads on wider devices. This PR uses a media query to apply the square dimensions only on narrower breakpoints.
Will need confirmation from @ab-gnm @aoifemcl15 @petternitter on whether the chosen breakpoint to switch between the two sizes is correct.
- Wrapped square ad CSS in a media query
=> Square Ads Only On Narrower Devices

ArticleTemplates/assets/scss/modules/_advert-slot.scss
**Jira ticket**: https://theguardian.atlassian.net/browse/LIVE-2671
This change allows us to show non-square ads as full width on Android. The square ads are still limited by the container height specified here (344px) and the ratio constraints in the native code.
Need to confirm this change works for iOS.
| | Before | After |
| --- | --- | --- |
| Horizontal ad | ![Screenshot_20210816-180834](https://user-images.githubusercontent.com/79363218/129603112-b1fc1797-be7a-473f-9607-a566d43f3005.png)|![Screenshot_20210816-174643](https://user-images.githubusercontent.com/79363218/129603143-4518cf25-47c6-467e-b4e1-331804c0b536.png)|
| Square ad |![Screenshot_20210816-180711](https://user-images.githubusercontent.com/79363218/129603124-1414ff1f-db6b-4671-a629-d36454cc3de8.png)|![Screenshot_2021081 …
=> [LIVE-2684] Remove width constraint on first ad slot

ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
Removes padding on all interactive and chart atoms, but keeps the white background. As requested by the visuals team so they can roll out dark mode changes for interactive atoms. Padding will now be added into atoms themselves.
FYI @ajwl 
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/129373881-d83b1cb1-035e-49fa-a873-54da17c063fb.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/129373938-fea5a700-0db0-4c35-b5d3-f648bd440a94.png" width="300px" />|
=> LIVE-2871: Remove white background and padding for interactive atoms

package-lock.json, package.json
Keeping dependencies up-to-date.
- Bump `d3` to `7.0.1`
=> Bump `d3` To `7.0.1`

ArticleTemplates/assets/scss/modules/_quiz.scss, ArticleTemplates/assets/scss/pillar/_colour.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeQuiz.scss, ArticleTemplates/assets/scss/themes/darkMode/_main.scss
Some changes were requested to make personality quizzes work in dark mode for GLabs, this PR also makes sure the same is true for editorial. 
Based on these designs by @benwuersching: https://www.figma.com/file/00tb4ffXvbReLDmptMVrjx/Quiz-colours?node-id=1%3A679 
| GLabs Light Mode | GLabs Dark Mode |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/133433871-4729e807-3fb4-4695-8482-54475653da9b.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/133433974-22eea0f9-339b-4f19-abb3-06ff1dc4d271.png" width="300px" />|
| Editorial Light Mode | Editorial Dark Mode |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/133434088-bc215cfd-5aa6-4c6d-b4ea-98c583f5257a.png" width="300px" />|<img …
=> LIVE-2854: Make sure personality quizzes have the correct styling and work in dark mode

package-lock.json, package.json
Github are deprecating the plain `git:` protocol. This switches to using the built-in GitHub support in npm instead.
- https://github.blog/2021-09-01-improving-git-protocol-security-github/
- https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls
- Switch `guardian/fence` to npm's GitHub URL syntax over `git:` protocol
=> Migrate From `git:` Protocol To `github:` Prefix

ArticleTemplates/assets/scss/modules/_advert-slot.scss
We don't want to show the premium upgrade banner on Guardian Labs pieces, as this is paid for content.
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/142417631-21ae92bb-82e7-4dd4-9277-3b29971dcba9.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/142417682-9797f5b7-89a7-4f91-b580-dca80559859a.png" width="300px" />|
Paired with @waisingyiu and @JamieB-gu
=> LIVE-3161: Remove premium ads cta when showing labs content

ArticleTemplates/assets/js/boot.js, ArticleTemplates/assets/js/bootstraps/common.js
* Adds an event listener for `set-height` messages from email embed iframes
* Allows the email embed iframe to resize itself, such as to show a reCAPTCHA challenge
=> Add listener for email embed resize messages

ArticleTemplates/assets/js/bootstraps/common.js
`iframe.contentWindow` and `event.source` could be null. Check they are not null before checking for equality
=> Check for null before comparing

ArticleTemplates/assets/scss/layout/_article--shared.scss
Fix bug in now and then interactive where on tablet the now photo is taller than the before photo and half the image is cropped (width ways).
The fix for this is very simple. By setting a max width of 570px for the interactives container, this prevents the container from reaching a width of 575px at which point something within the now/then interactive code causes the second image to have a width of 635px (about the width of the iFrame it is contained within). Because this is a max width is has no effect on devices with less wide displays/windows (e.g phones).
| --- | --- |
|<img src="https://user-images.githubusercontent.com/3285072/161799932-73c849e5-053e-489b-81db-5ad491246c28.png" width="300px" />|<img src="https://user-images.githubusercontent.com/3285072/161799957- …
=> [LIVE-3944] Fix tablet now then interactives sizing bug

ArticleTemplates/assets/js/bootstraps/common.js, package.json, test/spec/unit/bootstraps/common.test.js, test/spec/unit/bootstraps/liveblog.test.js, webpack.config.js
The PR updates the existing `fence` and `curl` dependencies to be provided via `npm` instead of directly from Github.
Something changed over the weekend so that Github now doesn't provide node dependencies without authenticated pulls. The ssh keys for `guardian-android` that we use on TeamCity aren't available inside the Docker container where the Android app is built. As a result, the build is unable to fetch the two dependencies that are provided from github - `fence` and `curl`. This is causing all Android builds to fail on TeamCity.
Moving to npm-hosted versions of these dependencies will help resolve the issue by removing the need for a gihub recognised ssh key inside the docker container.
=> Migrate `fence` and `curl` dependencies from GitHub to `npm`

ArticleTemplates/assets/scss/themes/darkMode/_darkModeLiveblog.scss, ArticleTemplates/assets/scss/type/_live.scss, ArticleTemplates/liveblogTemplate.html
This PR adds a blinking dot to liveblogs article title section in order to better indicate to users the liveness on a live blog. 
The accessibility was also tested both in ios and android, and the blinking dot is with no pulsation when the motion/animation is switched off in the device accessibility setting. 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/15894063/165324166-b93a8a74-4a8d-4684-8b4d-1f9c35fedede.png) | ![ezgif-1-f22ab65e00](https://user-images.githubusercontent.com/15894063/165323720-5d1f8566-bdc8-49d0-8e20-d18351403800.gif) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/15894063/165354895-e71e5cf0-92ca-410f-9852-eabee9c0e889.png) | ![ezgif-2-0ed1b7ca31](https://user-images.githubusercontent.com/ …
=> add blinking dot in liveblog kicker

ArticleTemplates/assets/scss/themes/darkMode/_darkModeArticle.scss
We recently introduced a new designType for newsletter tone articles. Without including this designType in the legacy templates dark mode selectors the articles do not render as expected in dark mode.
This change is part of a set of changes required:
- the capi client has been updated with the correct set of designTypes https://github.com/guardian/content-api-scala-client/pull/352
- given the latest capi client has been published, it should be consumed by mobile-apps-api https://github.com/guardian/mobile-apps-api/pull/1899
- after mapi uses the latest capi client, newsletter tone articles rendered via legacy templates will include a `body` tag with class `garnett--type-newsletter`
- given the above has taken place and the expected class is included in the body tag, the latest legacy …
=> Include newsletter designType in darkMode selectors

ArticleTemplates/articleTemplateImmersiveHeight.html, ArticleTemplates/assets/js/modules/immersive.js
On web the height of immersive header background images was reduced (https://github.com/guardian/dotcom-rendering/pull/4671). This change ensures consistency across mobile too.
Note that, because of the top margin calculation, specifying 80vh in these templates resulted in a much reduced background image size. I thought specifying 90vh more closely matched the output in web.
| --- | --- |
|<img src="https://user-images.githubusercontent.com/45561419/165104952-9e3ca535-545b-47c9-8ec5-cd15004f76b0.png" width="300px" />|<img src="https://user-images.githubusercontent.com/45561419/165102961-fded8723-b8f2-43fb-a701-0df501d576c0.png" width="300px" />|
| --- | --- |
|<img src="https://user-images.githubusercontent.com/45561419/165103989-f5c4dada-e5da-4213-a11 …
=> Reduce height of immersive header background images

package-lock.json, package.json
=> Bump `intersection-observer` Polyfill To 0.12.2

package-lock.json
Keeping dependencies up to date.
- Update `minimatch` to v3.1.2
- Update `nwsapi` to v2.2.2
- Update `istanbul-reports` to v3.1.5
=> Update `minimatch`, `nwsapi` and `istanbul-reports`

ArticleTemplates/assets/js/modules/youtube.js
This PR makes sure to concat the list of videos correctly, so when two videos appear with the said ID it renders the video in the correct position. 
The videos were being added to the beginning of the list rather than the end, and causing issues on render. The javascript did not know what position to render the video on the page and so appeared duplicated.
Here, we just make sure the concatenation of the list happens first, ensuring videos are appended in the correct order. So iOS can use the correct order of videos to show to the user. 
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/199222553-591c79dd-5f79-4d72-8bbf-e75e15febc5a.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/199222455-813c1ec4-415b-4000-85 …
=> LIVE:4733: Fix duplicate videos appearing on iOS

ArticleTemplates/interactiveTemplate.html
Documentary interactives are not loading in the app (the content never loads and we are shown only the loading screen):
While we have a workaround for this (redirecting users to an equivalent "video" article) the experience isn't the best, either for the reader or our colleagues in CP/user help.
This change updates the template for interactives to ensure the initialisation scripts used by documentaries can be executed without error, resulting in the documentary successfully loading.
When the documentary interactive attempts to load we can see the following error in the console:
^ I understand this to mean that we need to ensure an element exists before some function attempts to set an attribute.
This PR adds a new `main` element into the body of the interactive template. The reason for …
=> LIVE-4785: load documentary interactives

ArticleTemplates/assets/scss/modules/content/_prose.scss
It has been reported that "when an associated reference or side bar is dropped in an article, particularly lists,  it overrides/erases the heading for the next item, so you may not have a clue what it's referring to"
This happens particularly at larger font sizes, and has been noticed on a number of articles by both CP and readers via User Help.
This PR attempts to ensure that headings (h2 elements) remain visible, even at larger font sizes.
NB: the default property for the `overflow` property is `visible`, so I'm assuming we're ok to simply remove the property entirely for elements prose > h2.
Font size 6 (all h2s now visible):
| --- | --- |
|<img src="https://user-images.githubusercontent.com/45561419/201365164-4fdcc7a8-2731-45a7-b1e8-075fd71f8e27.png" width="300px" …
=> LIVE-4578: ensure h2 elements are visible at larger font sizes

ArticleTemplates/assets/js/bootstraps/liveblog.js, ArticleTemplates/liveblogTemplate.html
This fixes a bug where the kicker was missing from some live blogs. On line 41 in the` liveBlogTemplate.html` file we are displaying the `__SERIES__` as the kicker. The problem is, not every live blog will be part of a series. In these cases we need to revert to displaying the `__SECTION__` so that we are in line with the website. 
Jamie Byers has mentioned that there are some slightly more complicated rules around what to display as the "kicker" on Dotcom and therefore this change isn't necessarily "perfect". However, it should still cover the large majority of cases and will mean there is no more blank space where there should be a kicker. In any case, it probably isn't worth spending too much time on as the Apps Rendering rollout will make these templates obsolete in the near future. …
=> Fixed missing kicker in live blogs

ArticleTemplates/assets/js/bootstraps/liveblog.js
A previous PR fixed the missing kicker in live blogs: https://github.com/guardian/mobile-apps-article-templates/pull/1604
However, it also introduced a bug where the kicker colour is now the wrong colour on pillars other than news. This is because the original PR assumed it is necessary to give the kicker a faded colour, when in fact the default on light mode is white anyway. This PR now brings it in line with default behaviour.
The slight trade off here is that in dark mode the kicker will be slightly brighter than the headline text. This is probably better than a missing space where there should be a kicker, however. In any case, these templates are soon to be superseded by AR liveblogs so this is a somewhat temporary fix until they are in production. 
| Before | After | Dark mode |
| …
=> Remove setting of colour

ArticleTemplates/footballTemplateLiveblog.html
This adds a main media image to football liveblogs, to match behaviour seen in standard liveblogs
Paired with @marjisound 
| --- | --- |
|<img src="https://user-images.githubusercontent.com/19835654/207299626-bed57ea2-3342-4d1b-a547-a66dd1836375.png" width="300px" />|<img src="https://user-images.githubusercontent.com/19835654/207299728-72e9f597-da08-4697-8084-81b12a68bbd8.png" width="300px" />|
=> Add main media image to football liveblogs

ArticleTemplates/articleTemplateContainerImmersive.html, ArticleTemplates/assets/scss/modules/content/_meta.scss, ArticleTemplates/assets/scss/type/_immersive.scss
CP team reported that the main image caption / credit were not displayed on immersive articles.  We saw this problem with immersive articles when they were rendered using legacy templates.
The Editorials pointed out that for some pieces (such as [this one](https://www.theguardian.com/uk-news/2023/apr/29/the-crowd-were-saying-kill-him-kick-him-to-death-what-happened-to-the-people-who-protested-against-king-charles)), it was very important readers see the credit on the illustration. 
This PR fixed the problem by adding the image caption to immersive article templates.  We changed the template based on the same design as immersive articles rendered by AR.
The following PRs have been raised to make changes to the native apps in order to show the caption information with the updated template: …
=> LIVE-5221 show image credit in immersive articles

.github/workflows/ci.yml
See [this jira ticket](https://theguardian.atlassian.net/browse/LIVE-5541)
This adds a workflow script to build and publish the app templates as an npm package. I tested my changes by going into both the iOS and Android repos, manually changing their templates version numbers, and then running `npm install`. The new package was installed successfully. I then tested the build on the iOS repo and can confirm templates work as expected.
I paused all team city builds for templates whilst doing this work to ensure that duplicate packages we're not being published simultaneously. 
You can see the full successful workflow [here](https://github.com/guardian/mobile-apps-article-templates/actions/runs/5955128736)
In doing this the iOS/Android repos will no longer automatically pull in the latest …
=> Migrate build from Team City to Github Actions

.github/workflows/ci.yml
In a [previous pr](https://github.com/guardian/mobile-apps-article-templates/pull/1660) I removed some steps from a workflow that were necessary for the script to run properly.  In GitHub Actions, each job is a separate unit of work, and steps within a job execute in a fresh environment, hence I need to add these steps back in.
=> Restore checkout, setup node and install dependencies on ci script

.github/workflows/ci.yml
I think a double $$ is preventing the publish step from succeeding. Fingers crossed this works. 
I think it's most effective to test this after a merge to master, so I can be 100% sure that the scripts are executing correctly
=> Remove double $$

.github/workflows/ci.yml
Before the migration from TeamCity to Github actions mobile-apps-article-templates would run `npm run build` before publishing the build artifacts to npm and creating a new release. This adds back in that step so that css ends up in the npm release like it did before. 
Example of release without running `npm run build` https://www.npmjs.com/package/@guardian/mobile-apps-article-templates/v/1.0.888?activeTab=code
Example of release where `npm run build` was run https://www.npmjs.com/package/@guardian/mobile-apps-article-templates/v/1.0.858?activeTab=code
=> Build code before publishing to npm

ArticleTemplates/assets/js/bootstraps/audio.js
Ticket: https://theguardian.atlassian.net/browse/LIVE-5764
Hide existing podcast controls when native player is showing on article.
These provides 2 UX options.
- Place native audio controls in same position as HTML ones were.
- Place native audio controls somewhere else (floating at the bottom of article for example).
We may want to place the native audio player in the same position as the HTML based one, so this function returns it's position relative to the page top left corner. This position does not change as the content is scrolled, keeping it in sync with scrolling is the responsibility of the native app. As the height of a audio player might vary by platform / font size, the height in px can be passed to hidePodcastPlayer as number. e.g hidePodcastPlayer(100).
If the native app …
=> Hide and resize height of podcast player

ArticleTemplates/assets/scss/pillar/_arts.scss, ArticleTemplates/assets/scss/pillar/_lifestyle.scss, ArticleTemplates/assets/scss/pillar/_news.scss, ArticleTemplates/assets/scss/pillar/_opinion.scss, ArticleTemplates/assets/scss/pillar/_sport.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeMedia.scss, ArticleTemplates/assets/scss/themes/darkMode/_main.scss
I saw that the new play button on podcast article template (created in #1679 ) in *loading* state still showed the old yellow colour under dark mode.  It is expected to have the same colour as the button in stopped / playing states.  
The reason is that in dark mode, the legacy template has another CSS rule to set the colour of the button in loading state, which overrides the rule which is used for the colour in light mode.
This PR fixed the colour by adding a rule for dark mode to override the previous CSS rule.
I took this fix as part of the previous ticket #1679 
| --- | --- |
| Sport (dark) | Sport (dark) |
|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/bf8ade98-3b74-4383-95dc-fc001830bf4a" width="300px" />|<img …
=> LIVE-5793 Fix the colour of button in loading state in dark mode

.github/CODEOWNERS
So any PR opened will automatically have MSS as reviewers, and so anyone who needs to contribute to this codebase knows who to contact for help. This matches the equivalent CODEOWNERS file in MAPI.
=> Add MSS As CODEOWNERS

ArticleTemplates/assets/scss/themes/darkMode/_darkModeMedia.scss
It was reported that the colour of the play button in the new podcast audio control was incorrectly changed to yellow when it was being pressed.  Further examination showed that it happened under dark mode only.
With the web inspector, it was found that when the button was pressed, the CSS rule with the pseudo class `:active` (an example was shown below) was applied instead of the intended rule:
To fix the problem, new CSS rules have been defined for the colour of play button (in active or not) under dark mode:
The SCSS applies to all pillars.  I captured the screenshots for news and sport pillar as examples
| --- | --- |
| News | News |
| Pressed | Pressed |
|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/78400b91-f2e9-4b6d-bd30-c4d6 …
=> LIVE-6006 Fix the colour of play button when it is being pressed 

ArticleTemplates/assets/scss/modules/content/_meta.scss
This PR increases the margin on the bottom of the author pic, so that in the cases where the byline wraps around a line and there are both notifications and follow button visible. 
| --- | --- |
|![no-comment-author-wrap-before](https://github.com/guardian/mobile-apps-article-templates/assets/1202622/3b87c91b-db59-4074-aa6c-e8cb1e104c04)|![no-comment-author-pic-wrap](https://github.com/guardian/mobile-apps-article-templates/assets/1202622/b5ab4b08-7f3b-435a-ab65-5daee9f24f77)|
=> Increase the margin on the author image

.changeset/chatty-papayas-double.md, ArticleTemplates/articleTemplateContainerFeatures.html
We are working on the new listen-to-article feature for the app.  This PR adds the new listen-to-article control UI on the legacy templates for features design.
| Light Mode | Dark Mode |
| --- | --- |
|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/303543b0-0d01-401a-9e85-7ddfbf481624" width="300px" />|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/265b76a4-a253-4358-9fa2-78d305f2f51b" width="300px" />|
=> LIVE-6056 Add listen-to-article UI to features article template

README.md
Now that we've changed the github action for CI to use `changesets`, this PR adds the instructions on publishing the package to the `readme` doc.
=> Add instructions for publishing to npm repository

.changeset/honest-pandas-battle.md, ArticleTemplates/articleTemplateContainerImmersive.html
This PR adds the listen-to-article control UI to immersive design article template.
| Light | Dark |
| --- | --- |
|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/af8f7f10-940d-4b63-9425-69757417f2d2" width="300px" />|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/a6c32677-a1c7-492f-905a-aa015a627cad" width="300px" />|
=> LIVE-6055 Add listen to article UI to immersive article template

.changeset/swift-tigers-listen.md, ArticleTemplates/assets/js/bootstraps/article.js, ArticleTemplates/assets/js/bootstraps/football.js, ArticleTemplates/assets/js/modules/listen-to-article.js
This PR aims to add the new listen-to-article UI to football template.
The football template actually uses the standard article template to render the main part of the article, which we've already added the HTML snippet for the UI.  However, the Javascript functions for controlling the UI were not available in this football template.
This PR extracts these functions into a separate module JS so that it can be shared between article JS and football JS modules. 
| Light | Mode |
| --- | --- |
|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/166c1a91-9d04-4f97-8e20-9ea07e4f1fc6" width="300px" />|<img src="https://github.com/guardian/mobile-apps-article-templates/assets/89925410/56001a99-46f3-4e00-a016-04d8a02f0dc4" width="300px" />|
=> LIVE-6058 Add listen to article UI to football article template

.changeset/stale-dodos-join.md, ArticleTemplates/articleTemplateAlerts.html, ArticleTemplates/assets/js/modules/myGuardianFollowInit.js, ArticleTemplates/assets/scss/modules/_alerts.scss
This changes the display property of notifications button from `block` to `inline-block` because the issue with setting this to `block` means that the area of the whole region is clickable. 
[This video](https://github.com/guardian/mobile-apps-article-templates/assets/1202622/deb655f0-c5bb-49ed-9db7-c9e7349e3fb4) shows the problem. 
The original intent of using the display property `block` was to put the addition of a second button on a new line. This is now achieved by adding a break tag in the mark up instead.
=> Display buttons as inline-block

.changeset/nine-lies-report.md, ArticleTemplates/assets/js/modules/atoms/services.js
Editorials and users reported that audio atom does not work on this piece:
https://www.theguardian.com/us-news/2024/feb/26/ai-deepfake-quiz-spot-the-sham-audio-of-trump-and-biden
The audio atom should have been broken on legacy template for quite a while.
MAPI is using [atom-renderer](https://github.com/guardian/atom-renderer) to render atoms on legacy template, and this atom-renderer had a breaking change in this [PR](https://github.com/guardian/atom-renderer/pull/84).  Unfortunately, the legacy template was not updated for this change.
This PR updates the service object according to the requirement.
The audio atom worked properly when I tested this change locally: 
https://github.com/guardian/mobile-apps-article-templates/assets/89925410/d5dfd8d8-50c2-4ec9-890e-abffdb4f334b
=> LIVE-6342 Fix audio atoms

.changeset/tasty-buses-bow.md, ArticleTemplates/assets/js/bootstraps/atoms.js, ArticleTemplates/assets/scss/modules/_atoms.scss
Enable safe scrollies, which do not break out of their `iframe`s.
https://github.com/guardian/mobile-apps-article-templates/assets/76776/3cbd2628-95f3-4298-b6a6-f9806c333994
- https://github.com/guardian/dotcom-rendering/pull/10604
- https://github.com/guardian/interactive-generic-ai2html-scrolly/pull/6
=> Support scrollies

package-lock.json, package.json
Snyk identified vulnerability in a dependency introduced transitively through `changesets`.  This PR bumps `changesets` to the latest version to keep its dependencies more updated.
No changes to the templates are expected.  `changesets` is used during build time only.
=> Bump changesets version

.changeset/strange-suns-pretend.md, package-lock.json
Update package-lock.json so that it uses a newer micromatch version (4.0.7) to remove one of the Synk vulnerabilities
=> Update lock file to resolve dependency vulnerabilities

README.md
No matter how hard I tried, I could not get the app to use the correct version of the templates from a branch.
Finally I tried deleting both `package-lock.json` and `node_modules` - this seemed to do the trick to force npm to install the right versions (and regenerate those files). Maybe this will be helpful for any future users of this.
=> Update Readme to help iOS simulator users

.changeset/four-baboons-travel.md, package-lock.json, package.json
This explicitly adds a version of micromatch with vulnerability fix as outlined in the snyk report
| --- | --- |
=> Upgrade micromatch

.changeset/fifty-birds-brush.md, ArticleTemplates/assets/js/modules/ads.js, ArticleTemplates/assets/scss/modules/_advert-slot.scss, ArticleTemplates/assets/scss/themes/darkMode/_darkModeShared.scss
Remove the 'Support the Guardian' upsell from templates
Also centered the ad label text to align with web ad labels
The height of inline1 ad slots has not been updated as we still need to reserve space for taller ad sizes such as Teads video ads. The extra space has been approved by the commercial team.
| --- | --- |
| inline1 | inline1 |
|<img src="https://github.com/user-attachments/assets/7891896d-dc29-4b36-9d20-fbcf170e0cc6" width="300px" />|<img src="https://github.com/user-attachments/assets/e07bd144-2146-48bb-ba3a-5a1460a5b267" width="300px" />|
| inline2+ | inline2+ |
|<img src="https://github.com/user-attachments/assets/618fe7f6-2d6b-4752-9d80-43070bedd5f5" width="300px" />|<img src="https://github.com/user-attachments/assets/bc0fbaaf-6f73-4039-8c83-566bde025b11 …
=> Remove ad slot support message

.changeset/silent-frogs-relate.md, ArticleTemplates/assets/scss/themes/darkMode/_darkModeLiveblog.scss
Co-authored-by: Ravi <7014230+arelra@users.noreply.github.com>
This PR fixes dark mode for the match report 
| Platform | Before | After |
| --- | --- | --- |
| iOS | <img src="https://github.com/user-attachments/assets/1ba85127-2f1e-4039-b2b3-5e66666ce9d6" width="300px" />|<img src="https://github.com/user-attachments/assets/bc009404-5165-469f-9c75-88f22269e7f8" width="300px" />|
| Android | <img src="https://github.com/user-attachments/assets/621636fa-7669-4fed-975b-5fa4c9de1cdf" width="300px" />|<img src="https://github.com/user-attachments/assets/2cdb02da-35d5-43c1-97b4-6cdf727df838" width="300px" />|
=> fix match reports dark mode

.changeset/ninety-hairs-float.md, ArticleTemplates/galleryImageViewCaption.html
Fixes a bug where the caption has `h2` element. Putting the `<h2>` within the `<p>` was breaking the CSS selectors and the styles were not correctly applied. 
| --- | --- |
|<img src="https://github.com/user-attachments/assets/0a21c9c2-e722-476c-a61e-b0fea4ad73af" width="300px" />|<img src="https://github.com/user-attachments/assets/e15ecd87-f629-4f64-a243-5ab787e4cee4" width="300px" />|
Fixes part of [#12637](https://github.com/guardian/dotcom-rendering/issues/12637)
=> replace p tag by div for gallery view caption
